### ISSUE TITLE
MQTT to MQTT-SN Gateway functionality

### ISSUE THREAD

**Issue by aberkecz** [eclipse/paho.mqtt-sn.embedded-c#100]
Hi,

First of all, thank you for your hard work on this amazing project.

We have successfully used it to translate MQTT-SN messages to MQTT ones with much success. However, we are having troubles figuring out if we could use this project to translate regular MQTT messages sent by a VerneMQ broker to MQTT-SN messages so we could send information back to our low-powered devices.

Does this project present such functionality?

**Comment by aberkecz** [comment]
We tested it and it seems to work just fine automagically :)

However, I would propose a minor change in the first sentence of the Gateway's README.md to make it more explicit that it works both way.

From this:
```
MQTT-SN requires a MQTT-SN Gateway which acts as a protocol converter to convert MQTT-SN messages to MQTT messages.
```

To this:
```
MQTT-SN requires a MQTT-SN Gateway which acts as a protocol converter to convert MQTT-SN messages to and from MQTT messages.
```

I would be happy to issue a PR if you agree.

**Comment by ty4tw** [comment]
Hi,

Thank you.
Any PR is appreciated.
