### ISSUE TITLE
Message ID is not allowed to be 0

### ISSUE THREAD

**Issue by mansk789** [eclipse/paho.mqtt-sn.embedded-c#101]
Hi

I discovered, that message with ID 0, are not added to the "TopicIdMap" (in MQTTSNPublishHandler::handlePublish). And it ends up in the following error "PUBACK from the Broker is invalid. PacketID : 0000"

I couldn't find any hint for this specific behavior in the specification, so I assume it's a bug. Is this correct or have I overseen something?

Thanks

**Comment by ty4tw** [comment]
Hi, 
In case of QoS0, megID will be 0.

see, P14 line 7 of specification.
MsgId: same meaning as the MQTT “Message ID”; only relevant in case of QoS levels 1 and 2, otherwise coded 0x0000.
