### ISSUE TITLE
Gateway Tester - SLEEP MODE

### ISSUE THREAD

**Issue by dkcodeguy** [eclipse/paho.mqtt-sn.embedded-c#102]
Hi,
I'm currently testing MQTTSNGateway on Raspberry Pi 3 and running Gateway Tester on my pc. I found out that keep-alive must be shorter than sleep duration. If it’s the other way around, it takes into account for sleep duration the value of keep-alive.
Current configuration:
```
/*------------------------------------------------------
 *    Client Configuration  (theMqcon)
 *------------------------------------------------------*/
MQTTSNCONF = {
	60,            //KeepAlive [seconds]
	true,          //Clean session
	120,           //Sleep duration [seconds]
	"",            //WillTopic
	"",            //WillMessage
    0,             //WillQos
    false          //WillRetain
};
```
If I want that client sleeps for 120 sec, client will send PINGREQ every 60 sec (keep-alive value), wouldn't it be correct if  client sends just one PINGREQ at the end of sleep duration?

**Comment by ty4tw** [comment]
Hi,
The client must send PINGREQ before the Broker disconnect it.
which means KeepAlive must be longer than sleep duration.

Sleep duration means how often the client checks subscribed messages are published from the Broker. 
see, 6.14 Support of sleeping clients P.25 of the specification.

**Comment by dkcodeguy** [comment]
Hi,
Thank you for answering. In the default code provided the sleep duration is longer than keep-alive. I tested it now and if it's equal it works fine, but if keep-alive is longer than sleep duration, it will change the state from asleep to awake after the keep-alive timer runs out and the gateway doesn't send any buffered messages to the client. Is that correct?

**Comment by ty4tw** [comment]
Hi,

I will check it.
Could you attach a log?

Tomoaki  YAMAGUCHI

2018-02-07 16:48 GMT+09:00 dkcodeguy <notifications@github.com>:

**Comment by dkcodeguy** [comment]
Hi,
Configuration is keep-alive 120s and sleep duration 60s:
  ```
20180207 081309.395   SEARCHGW          <---  C$
  20180207 081309.395   GWINFO            --->  ^$

  20180207 081309.396   CONNECT           <---  G$
  20180207 081309.398   CONNECT           --->  G$
  20180207 081309.497   CONNACK           <---  G$
  20180207 081309.497   CONNACK           --->  ^$

  20180207 081309.498   SUBSCRIBE   0001  <---  GatewayTestCli$
  20180207 081309.498   SUBSCRIBE   0001  --->  G$
  20180207 081309.498   SUBACK      0001  <---  G$
  20180207 081309.499   SUBACK      0001  --->  GatewayTestCli$
  20180207 081309.550   DISCONNECT        <---  G$
  20180207 081309.550   DISCONNECT        --->  ^$

  20180207 081326.442   PUBLISH     0001  <---  G$
  20180207 081326.442   PUBLISH           --->  G$
  20180207 081326.442   GatewayTestClient is sleeping. the packet was save$
  20180207 081326.442   PUBACK      0001  --->  G$

  20180207 081509.517   PINGREQ           <---  G$
  20180207 081509.517   PUBLISH     0001  --->  GatewayTestCli$
  20180207 081509.518   PINGREQ           --->  G$
  20180207 081509.518   PINGRESP          <---  G$
  20180207 081509.518   PINGRESP          --->  ^$
  20180207 081509.518   PUBACK      0001  <---  GatewayTestCli$

  20180207 081509.519   CONNECT           <---  G$
  20180207 081509.519   CONNACK           --->  ^$
  20180207 081515.389 BrokerSendTask   stopped.
```
If you look at the time log you can see that PINGREQ arrives 120s after DISCONNECT. Client gets messages, maybe i did something wrong before.

**Comment by ty4tw** [comment]
OK, fine.

**Comment by dkcodeguy** [comment]
Could you just explain if it's correct that client sleeps for the duration of keep-alive value if it is longer than the sleep duration. Like it's shown in log above.
Thanks.

**Comment by ty4tw** [comment]
Yes, follows log is a same as Figure 5 in specification.

20180207 081509.517   PINGREQ           <---  G$
20180207 081509.517   PUBLISH     0001  --->  GatewayTestCli$
20180207 081509.518   PINGREQ           --->  G$

**Comment by ty4tw** [comment]
You might misunderstand the gatewayTester applicaton. The purpose  is
testing gateway. So,it NEVER sleep when you send DISCONNECT with sleep
duration.


2018/02/08 16:48 "dkcodeguy" <notifications@github.com>:

**Comment by dkcodeguy** [comment]
This clears things up. Thanks.
