### ISSUE TITLE
topic name has 2 chars segment fault

### ISSUE THREAD

**Issue by boycechen** [eclipse/paho.mqtt-sn.embedded-c#104]
when client subscribe with 2 chars topic name, ex. "aa" or "tt", the daemon MQTTGATEWAY exception with segment fault

subscribe example:
      mqtt-sn-sub -h mqtt_server -p port -t 'aa'
when subscribed, the MQTTSNGATEWAY will exited with segmentation fault!

**Comment by suchomar** [comment]
Hi,
I have just made  pull request which should fix also this problem.  https://github.com/eclipse/paho.mqtt-sn.embedded-c/pull/103/commits/2e9abb8fbb79aa9f0784f41a5cb003434ae66b7d

You can try and test this branch  https://github.com/tieto/paho.mqtt-sn.embedded-c/tree/develop if you want.

**Comment by boycechen** [comment]
It's ok now，tks！

**Comment by ty4tw** [comment]
According to the eclipse pull request rule, contributor is required contributors agreement in case of more than 200 lines without copy right notice. This pull request is less than 200 lines but  copy right notice is included. I'm not sure but avoid the reagal problem later, you should submit the eclipse contributed agreement. And clearly mention your copy right portion in the source code.
