### ISSUE TITLE
Contributing guideline seems to be outdated

### ISSUE THREAD

**Issue by suchomar** [eclipse/paho.mqtt-sn.embedded-c#106]
It looks like [Eclipse CLA](https://www.eclipse.org/legal/CLA.php) is deprecated.
Should [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php) be use instead?

**Comment by ty4tw** [comment]
yes it is.

**Comment by icraggs** [comment]
Yes, thanks.  I've updated the contributing guidelines on some other repositories.  I will do this one in the next day or two.

**Comment by icraggs** [comment]
Updated.  Thanks for pointing this out.
