### ISSUE TITLE
gateway with xbee sensornet type   killed by ctrl+c  but not  exit and still hang there 

### ISSUE THREAD

**Issue by boycechen** [eclipse/paho.mqtt-sn.embedded-c#107]
I want compile a gateway work in xbee network , but when i press ctrl+c , the gateway exited but can not exit to linux console  ,only hang there 
when i press ctrl + z it stopped on background

**Comment by ty4tw** [comment]
Hi,
Thank you for your info.
Can you attach the log?


2018/02/24 17:17 "boycechen" <notifications@github.com>:

**Comment by boycechen** [comment]
Hi,
    no log information exists when I run Build/MQTT-SNGateway and press ctrl + c 
    only show : 
 
                 20180226  101931.209   PacketHandleTask   stopped.
                 20180226  101931.209   ClientSendTask        stopped.
                 20180226   101931.209  BrokerSendTask      stopped.
                 20180226   101931.547  BrokerRecvTask       stopped.
                 
     and always stay here not exit to linux shell console

**Comment by ty4tw** [comment]
Hi,

Thanks.
ClientRecvTask doesn't stop.

the time out procedure of serial port read() function is not implemented.
This is a bug.

My XBee was broken, it takes time to fix the bug.
please, wait and see.

Tomoaki  YAMAGUCHI

2018-02-26 11:23 GMT+09:00 boycechen <notifications@github.com>:

**Comment by ty4tw** [comment]
Hi, boycechen

I did not debug this code. ( just write down)    
can you try this code.    
```
#include <sys/time.h>
#include <sys/types.h>
#include <sys/select.h>

int XBee::recv(uint8_t* buf, uint16_t bufLen, SensorNetAddress* clientAddr)
{
	uint8_t data[128];
	int len;

	while ( true )
	{

		if ( (len = readApiFrame(data)) > 0 )
		{

			if ( data[0] == API_RESPONSE )
			{
				memcpy(clientAddr->_address64, data + 1, 8);
				memcpy(clientAddr->_address16, data + 9, 2);
				len -= 12;
				memcpy( buf, data + 12, len);
				return len;
			}
			else if ( data[0] == API_XMITSTATUS )
			{
				_respCd = data[5];
				_respId = data[1];
				_sem.post();
			}
		}
		else
		{
		    return 0;
		}
	}
}

bool SerialPort::recv(unsigned char* buf)
{
    struct timeval timeout;
    fd_set rfds;
    FD_ZERO(&rfds);
    FD_SET(_fd, &rfds);
    timeout.tv_sec = 0;
    timeout.tv_usec = 500000;    // 500ms
    if ( select(1, &rfds, 0, 0, &timeout) > 0 )
    {
        if (read(_fd, buf, 1) > 0)
        {
            D_NWSTACK( " %02x",buf[0] );
            return true;
        }
    }
    return false;
}
```

**Comment by boycechen** [comment]
thanks for your reply.

I notice clientrecvtask not stopped. but I don't known why?

no effect after I try your code , can you tell you where the gateway log locate?

**Comment by ty4tw** [comment]
Log is just shown on the screen. so you need to redirect the stdout to a file.

could you insert printf() statement as follows and check the timeout happens every 500ms:   
```
bool SerialPort::recv(unsigned char* buf)
{
    struct timeval timeout;
    fd_set rfds;
    FD_ZERO(&rfds);
    FD_SET(_fd, &rfds);
    timeout.tv_sec = 0;
    timeout.tv_usec = 500000;    // 500ms
    if ( select(1, &rfds, 0, 0, &timeout) > 0 )
    {
        if (read(_fd, buf, 1) > 0)
        {
            D_NWSTACK( " %02x",buf[0] );
            return true;
        }
    }
    printf("XBee recv timeout\n");
    return false;
}
```

**Comment by boycechen** [comment]
sorry for my mistake, it's ok now and it can exit to linux console when i press ctrl + c

when no xbee data , it always show "XBee recv timeout"

**Comment by ty4tw** [comment]
Ok, I will commit this change.
Thank you for your help.
