### ISSUE TITLE
Using wildcard in subscribe message when sleep mode.

### ISSUE THREAD

**Issue by krzysztofsroczynski** [eclipse/paho.mqtt-sn.embedded-c#121]
Hi,
I am subscribed with topic using wildcard (+).
When i go to sleep mode i send every duration ping request.
If during sleep mode Broker publish message to my client, this message is saved. If publish message send by the Broker is send for the first time Gateway must send registration first, and then publish message.
So when i send ping request to the Gateway, i receive only register message without publish message.

### 

> 20180717 135258.291   DISCONNECT        <---  samd21                              18 00 0A
>      PacketHandleTask gets DISCONNECT      from the client.
> Client Status = Asleep
> 20180717 135258.291   DISCONNECT        --->  samd21                              18
> sendto 10.10.4.137:10000 length = 2
> 
> 20180717 135300.888   PUBLISH     0000  <===  samd21                              30 5A 00 3A 76 31 2F 73 62 2F 38 61 62 65 63 63 33 31 2D 38 39 30 30 2D 34 38 39 36 2D 39 39 37 37 2D 61 39 30 62 37 30 33 65 66 35 31 35 2F 63 6F 6E 66 69 67 2D 74 61 73 6B 2F 66 61 6E 7B 22 69 64 22 20 3A 20 22 66 61 6E 22 2C 20 22 76 61 6C 75 65 22 20 3A 20 22 6F 6E 22 7D
>      PacketHandleTask gets PUBLISH  0000 from the broker.
> 20180717 135300.888   PUBLISH           --->  samd21                             is sleeping. a message was saved.
> 20180717 135300.888    samd21 is sleeping. the packet was saved.
> recved from 10.10.4.137:10000 length = 8
> __recved unicast from :10000
> 
> 20180717 135308.378   PINGREQ           <---  samd21                              16 73 61 6D 64 32 31
>      PacketHandleTask gets PINGREQ      from the client.
> Client Status = Awake
>      PacketHandleTask gets PUBLISH  0000 from the broker.
> 20180717 135308.378   PINGREQ           ===>  samd21                              C0 00
> 20180717 135308.378   REGISTER    0001  --->  samd21                              0A 00 03 00 01 76 31 2F 73 62 2F 38 61 62 65 63 63 33 31 2D 38 39 30 30 2D 34 38 39 36 2D 39 39 37 37 2D 61 39 30 62 37 30 33 65 66 35 31 35 2F 63 6F 6E 66 69 67 2D 74 61 73 6B 2F 66 61 6E
> sendto 10.10.4.137:10000 length = 64
> 20180717 135308.378   PINGRESP          <===  samd21                              D0 00
>      PacketHandleTask gets PINGRESP      from the broker.
> Client Status = Asleep
> 20180717 135308.378   PINGRESP          --->  samd21                              17
> sendto 10.10.4.137:10000 length = 2
> recved from 10.10.4.137:10000 length = 7
> __recved unicast from :10000
> 20180717 135308.394   REGACK      0001  <---  samd21                              0B 00 03 00 01 00
>      PacketHandleTask gets REGACK  0001 from the client.
> Client Status = Asleep

The reason for this is in MQTTSNPublishHandler.cpp in:
```
topicId.data.id = id;
snPacket->setPUBLISH((uint8_t) pub.header.bits.dup, (int) pub.header.bits.qos,
	(uint8_t) pub.header.bits.retain, (uint16_t) pub.msgId, topicId, (uint8_t*) pub.payload,
	pub.payloadlen);
client->getWaitREGACKPacketList()->setPacket(snPacket, regackMsgId);
```
Shouldn't it be simple send publish message to client:

```
topicId.data.id = id;
snPacket->setPUBLISH((uint8_t) pub.header.bits.dup, (int) pub.header.bits.qos,
	(uint8_t) pub.header.bits.retain, (uint16_t) pub.msgId, topicId, (uint8_t*) pub.payload,
	pub.payloadlen);
evrg = new Event();
evrg->setClientSendEvent(client, snPacket);
_gateway->getClientSendQue()->post(evrg);
```

**Comment by ty4tw** [comment]
Hi,
thank you for your information.
Gateway has to hold PINGRESP until  receiving all REGACK and finish to send all PUBLISH packets.  
Cause of this issue is  send PINGRESP to the client  before REGACK returned, so client is Asleep again before to send PUBLISH.  Figure 5:sleep procedure in specification shows only PUBLISH, therefore I did not think the case that PUBLISH packet has wild card matching topic. 
I will fix this bug after coming back from my summer vacation.

<pre>
<dev>
/*
 *  PINGREQ
 */
void MQTTSNConnectionHandler::handlePingreq(Client* client, MQTTSNPacket* packet)
{
	MQTTGWPacket* msg = 0;

	if ( client->isSleep() || client->isAwake() )
	{
		while  ( ( msg = client->getClientSleepPacket() ) != 0 )
		{
			// ToDo:  This version can't re-send PUBLISH when PUBACK is not returned.
			client->deleteFirstClientSleepPacket();  // pop the que to delete element.

			Event* ev = new Event();
			ev->setBrokerRecvEvent(client, msg);
			_gateway->getPacketEventQue()->post(ev);
		}

               <b>//ToDo:  Wait until All PUBLISH packets are sent to the client </b>   

	}

	/* send PINGREQ to the broker */
	MQTTGWPacket* pingreq = new MQTTGWPacket();
	pingreq->setHeader(PINGREQ);
	Event* evt = new Event();
	evt->setBrokerSendEvent(client, pingreq);
	_gateway->getBrokerSendQue()->post(evt);
}
</dev>
</pre>

**Comment by ty4tw** [comment]
Hi,
I fixed the bug before a summer vacation.  
my flight will depart 12 hours later.

Try the new Gateway in development branch.

**Comment by krzysztofsroczynski** [comment]
Hi again :)
It works now. Thank you very much.
