### ISSUE TITLE
Sleep mode and Broker publish message

### ISSUE THREAD

**Issue by krzysztofsroczynski** [eclipse/paho.mqtt-sn.embedded-c#122]
Hi,
Client go to sleep mode (sends DISCONNECT with duration) and within duration Broker sends PUBLISH message. Gateway will store this message for future delivery (as soon as he gets PINGREQ from Client). But if Client goes to active mode (sends CONNECT) and for some reason never goes back to sleep mode Gateway will never deliver Brokers PUBLISH message?
Is it a specification problem or inside Gateway only?

**Comment by ty4tw** [comment]
Hi,
I reproduced the same bug.
the Gateway should send stored PUBLISH packet.

**Comment by ty4tw** [comment]
Fixed.

**Comment by krzysztofsroczynski** [comment]
Hi again :)
It works now. Thank you very much :)))
