### ISSUE TITLE
Switch to cmake as build tool

### ISSUE THREAD

**Issue by S3ler** [eclipse/paho.mqtt-sn.embedded-c#131]
Hi,

like already mention in #124 I can write a cmake file.

I offer you an adapted [CMakeLists.txt-file](https://gist.github.com/S3ler/fe77762a2964a1330bdb633ae6858d5a) which i wrote for myself to include the MQTTSNGatewy in my projects.
So each of you who wants to use cmake can use it.
I provides exactly the same functionality and variable-naming like the [current](https://github.com/eclipse/paho.mqtt-sn.embedded-c/commit/1ce32c73399074fb345a4ae5818ae6c0b4fae639) version of the MQTTSNGateway's Makefile.

Usage:

Copy it into paho.mqtt-sn.embedded-c/MQTTSNGateway.

```
cmake -G"Unix Makefiles"
make
make install
```
Output is the same (binaries and config-files are next to paho.mqtt-sn.embedded-c git location).

I just wanted to share my work with you, to decrease your work :) .
If you really want to switch to cmake, let me know i create a pull-request then.

**Comment by ty4tw** [comment]
Hi,
Thank you for your proposal. 
When it will be needed, I will ask a favor of you.
Thank you for your cooperation again.
