### ISSUE TITLE
Securing the gateway

### ISSUE THREAD

**Issue by FuzzyPones** [eclipse/paho.mqtt-sn.embedded-c#133]
Hello everyone,

I wonder how to secure message sending besides SSL and setting clients in clients.conf specifically.
In my use-case i have 1 to n devices that i do not know the clientID of or it has a specific pattern like "Client_kufakdhsffdsfg" .

You can set a username and password on the mosquitto broker so i wondered if something similiar is possible with this Gateway.
Is forwarding maybe a solution for this? From what i have read you can encapsulate messages with this. Could i encapsulate an MQTT message with username and password and forward it?
I would still have the Problem with the unknown client-id though ...

I am not so super fit in MQTT so excuse my noobishness.

**Comment by ty4tw** [comment]
Set a user name and password of the gateway by a gateway.conf.
All clients can share the same name and password.

**Comment by FuzzyPones** [comment]
So if i get it right:
I configure the clients in clients.conf, set a topic for a user who has a password for a topic in mosquitto and the clients that are allowed by clients.conf will use the password configured in gateway.conf, right?

What if i want more than one username / password combination? Set up more gateways ?
It is not possible to forward username and password through the gateway?

What if i don't care about the client's ID but want to allow them to send messages when the username / password is correct?

**Comment by ty4tw** [comment]
MQTT-SN CONNECT message has no user name and password. This means the
protocol does not support what you want to do.

2018年8月28日(火) 0:59 Barry <notifications@github.com>:
