### ISSUE TITLE
Persistenet subscription for long topics

### ISSUE THREAD

**Issue by Biribu** [eclipse/paho.mqtt-sn.embedded-c#137]
I am having some kind of issue while using persistent subscriptions with normal topics.

I am trying to subscribe to a long topic (something like "topic/config/123") with some devices and while those devices are connected to the broker, they keep receiving all frames sent by another client.

But, in case the "receiver" device disconnects (It is already subscribed) and the "publisher" client publishes something, once the receiver is connected again that frame is not received by it.

I have tried resubscribing after receiving connack from broker but nothing happens.

I have checked and clean session is not selected. Is there any other requirement to keep permanent subscription through different sessions? Maybe I am doing something wrong.

**Comment by ty4tw** [comment]
Hi,

when the receiver re-connects, client is required to subscribe Topics again.

Tomoaki  YAMAGUCHI

2018-09-19 20:07 GMT+09:00 PMartinez <notifications@github.com>:

**Comment by icraggs** [comment]
@ty4tw is that always true, Tomoaki?  If the clean is connected non-cleansession, don't we keep that setting in the MQTT connection to the MQTT broker?  Then if the MQTT-SN client reconnects non-cleansession again, wouldn't the MQTT subscription still exist? 

Thanks.

**Comment by Biribu** [comment]
@ty4tw How can that be possible? Then, My receivers should not be able to receive anything once they connect after some time disconnected if all subscriptions are deleted. Is this behaviour right?

**Comment by ty4tw** [comment]
Hi Ian,

No subscriptions are deleted.
This is not a specification, it is a constraint on gateway implementation.

If GW keeps client instances after DISCONNECT, when the client instance achieved the max number of client, one zombie  instance is deleted to CONNECT a new client.
after that when the deleted client CONNECT again,  how does it know that SUBSCRIBE is required this time?   
 Therefore, I think it would be easier to run CONNECT and SUBSCRIBE as a series of flow all the time for a client.
