### ISSUE TITLE
What is the correct way to run a Gateway in raspberry over Xbee?

### ISSUE THREAD

**Issue by fstovarr** [eclipse/paho.mqtt-sn.embedded-c#138]
I'm trying use a raspberry as gateway with Xbee module connected in serial port. The communication is successful, I can see when the frame arrives to gateway with valid checksum, but seems that the message is never forwarded.
I have been with this problem for several days and I have not been able to solve it, however I think that the error can be for lack of configuration of something that maybe I have not seen.

**Comment by ty4tw** [comment]
Hi,
Thank you for your question.
Could you attach a log of GW?
What kind of client program are you using?

**Comment by fstovarr** [comment]
I'm just receiving these dataframes:
00 01 03 84
Error: ClientSendTask can't send a packet to the client Unknown Client !.

And the client is the ascyncMQTT-SN of your repository.

**Comment by fstovarr** [comment]
The problem was the client version that we used, the arduino script AsyncClient seems not to be compatible. 
Thanks for the response.

**Comment by fstovarr** [comment]
After of many tests, I can run client successfully. The problem was the use of Transparent Mode in the Xbee Routers instead of the API Mode, this was causing a double packaging in the Xbee protocol, after this change the client run well.

Very thanks.

**Comment by ty4tw** [comment]
Hi,
Thank you for your information.
