### ISSUE TITLE
Disconnect procedure

### ISSUE THREAD

**Issue by rconen** [eclipse/paho.mqtt-sn.embedded-c#139]
Hi,

We are setting up an environment for low power sensors using the Paho MQTT-SN Gateway.

Everything works well however we came along the following situation.

We notice in some setups that the connection between the gateway and MQTT broker gets dropped because of proxies and/or load balancers.
Once the gateway tries to communicate with the broker it notices this and throws a 'Connection reset by peer (104)' error.
When this happens the SN client is not notified about this.

What is the best way to react on this?

- Should the SN Gateway send a disconnect back to the SN client?
- Is there a possibility to use keep alive on the TCP client connection to the broker?
- Other suggestions...

**Comment by rconen** [comment]
Thanks for responding this quickly.

I have also started the discussion with our hardware/firmware department.

Regarding this topic. We are talking about a solution where the sensors are sleeping and use as less power when possible. Additionally the telecom provider will charge per message meaning that it is preferred not to use the PINGREQ and PINGRESP when not needed.

Within the duration transmitted with the connect message a publish is sent. Because of this we do not use the PINGREQ.
We also notice that when the gateway is restarted the client is not notified about this, the next message from the client will be discarded until the client reconnects.

The following we noted in chapter 5.4.21 DISCONNECT in the MQTT-SN Protocol Specification v1.2

> A server or gateway may also sends a DISCONNECT to a client, e.g. in case a gateway, due to an error, cannot map a received message to a client.

Any ideas/suggestions about this situation?

**Comment by ty4tw** [comment]
Hi,
Use QoS1.

Tomoaki  YAMAGUCHI


2018年10月17日(水) 22:16 Ronald <notifications@github.com>:

**Comment by ty4tw** [comment]
>We also notice that when the gateway is restarted the client is not notified about this, the next message from the client will be discarded until the client reconnects.

PUBLISH with QoS1.
