### ISSUE TITLE
Segmentation Fault When Running MQTT-SN Gateway Tester

### ISSUE THREAD

**Issue by bryangwj** [eclipse/paho.mqtt-sn.embedded-c#144]
Hi, I have just installed the MQTT-SN Gateway as well as the MQTT-SN Gateway Tester. However, when running the tester, I will run into a segmentation fault at "Step 0: Subscribe predef topic1". 

In addition, when I run the MQTT-SNPubQOS-1, I will receive another error message stating "Error: Client is not connecting, message has been discarded".

**Comment by ty4tw** [comment]
Hi,

I think client.conf and predefinedTopic.conf  which define clients and predefine topics  is not fit for your situation.
Check those file's comment.
I will write some manual about client.conf and predefinedTopic.conf near future.
Thank you for your Issue.
