### ISSUE TITLE
mqtt-sn-gateway cross-compiled and it seems crased on the startup

### ISSUE THREAD

**Issue by ranjitsinh-rathod** [eclipse/paho.mqtt-sn.embedded-c#148]
Hi
I am new for the mqtt-sn-gateway and have cross compiled this package for my gateway. Now when I am trying to run this application it is not able to start and crashed into startup only.

I have used the default config files only.

I am getting below prints on the start:

terminate called after throwing an instance of 'MQTTSNGW::Exception'
  what():   Can't open the sensor network.

Can you please suggest what can be the issue?

Many thanks.

**Comment by ranjitsinh-rathod** [comment]
One update:
When I have enabled debug prints from the MQTTSNGWDefined.h files, I got the output as below:
**error Multicast IP_ADD_MEMBERSHIP in UDPPort::open**
terminate called after throwing an instance of 'MQTTSNGW::Exception'
  what():   Can't open the sensor network.

Aborted (core dumped)

**Comment by ty4tw** [comment]
Hi ranjitsinh,

Sorry for the late reply.
Dose your environment allow to use Multicast UDP?

**Comment by ranjitsinh-rathod** [comment]
Thanks, Tomoaki.

When I have done further debugging, I have resolved the issue with increasing multicast group count from using below.

$ echo 20 > /proc/sys/net/ipv4/igmp_max_memberships

As a default, in my systerm, this variable is set to zero and so it is unable to add an entry in a multicast group.
