### ISSUE TITLE
Question regarding unsubscribe messge

### ISSUE THREAD

**Issue by aflo1** [eclipse/paho.mqtt-sn.embedded-c#149]
Hello,

Using MQTT-SN Gateway, I subscribed to a topic, published a message to the same topic and received the posted message. Everything  worked correctly.
However after having unsubscribed from the above topic I still received published messages posted on the unsubscribed topic.

Following is the MQTT-SNGatewayTester output:

 ***************************************************************************
 * MQTT-SN Gateway Tester
 * Part of Project Paho in Eclipse
 * (http://git.eclipse.org/c/paho/org.eclipse.paho.mqtt-sn.embedded-c.git/)
 *
 * Author : Tomoaki YAMAGUCHI
 * Version: 2.0.0

 ***************************************************************************
Attempting to Connect the Broker.....
sendto 225.1.1.1      :1883   03 01 00

recved 185.215.193.15 :1883   03 01 00
  recv SEARCHGW
recved 185.215.193.15 :10000  03 02 01

  recv GWINFO
sendto 185.215.193.15 :10000  17 04 04 01 00 3c 47 61 74 65 77 61 79 54 65 73 74 43 6c 69 65 6e 74
  send CONNECT
recved 185.215.193.15 :10000  03 05 00
  recv CONNACK

 Connected to the Broker

 Attempting OnConnect.....
sendto 185.215.193.15 :10000  11 12 20 00 01 74 79 34 74 77 2f 74 6f 70 69 63 31
  send SUBSCRIBE

sendto 185.215.193.15 :10000  11 12 20 00 02 74 79 34 74 77 2f 74 6f 70 69 63 32
  send SUBSCRIBE
recved 185.215.193.15 :10000  08 13 20 00 01 00 01 00
  recv SUBACK
 Topic "ty4tw/topic1" Id : 1 was Subscribed.

recved 185.215.193.15 :10000  08 13 20 00 02 00 02 00
  recv SUBACK
 Topic "ty4tw/topic2" Id : 2 was Subscribed.

 OnConnect complete
 Test is Ready.

**** Step0:Subscribe predef topic1 is canceled ****

**** Step1:Publish topic1 is canceled ****

**** Step2:Publish topic2 start ****
sendto 185.215.193.15 :10000  1f 0c 20 00 02 00 03 70 75 62 6c 69 73 68 20 22 74 79 34 74 77 2f 74 6f 70 69 63 32 22 20 0a
  send PUBLISH
recved 185.215.193.15 :10000  07 0d 00 02 00 03 00
  recv PUBACK
 Topic "ty4tw/topic2"  Id : 2 was Published.

**** Step2:Publish topic2 complete ****

recved 185.215.193.15 :10000  1f 0c 20 00 02 00 01 70 75 62 6c 69 73 68 20 22 74 79 34 74 77 2f 74 6f 70 69 63 32 22 20 0a
  recv PUBLISH
sendto 185.215.193.15 :10000  07 0d 00 02 00 01 00
  send PUBACK

Topic2 recv.
Payload -->publish "ty4tw/topic2" 　<--

**** Step3:Subscribe topic2 is canceled ****

**** Step4:Publish topic2 is canceled ****

**** Step5:Unsubscribe topic2 start ****
sendto 185.215.193.15 :10000  11 14 00 00 04 74 79 34 74 77 2f 74 6f 70 69 63 32
  send UNSUBSCRIBE
recved 185.215.193.15 :10000  04 15 00 04
  recv UNSUBACK
 Topic  "ty4tw/topic2"  was Unsubscribed.

**** Step5:Unsubscribe topic2 complete ****

**** Step6:Publish topic2 start ****
sendto 185.215.193.15 :10000  1f 0c 20 00 02 00 05 70 75 62 6c 69 73 68 20 22 74 79 34 74 77 2f 74 6f 70 69 63 32 22 20 0a
  send PUBLISH
recved 185.215.193.15 :10000  07 0d 00 02 00 05 00
  recv PUBACK
 Topic "ty4tw/topic2"  Id : 2 was Published.

**** Step6:Publish topic2 complete ****

recved 185.215.193.15 :10000  1f 0c 20 00 02 00 02 70 75 62 6c 69 73 68 20 22 74 79 34 74 77 2f 74 6f 70 69 63 32 22 20 0a
  recv PUBLISH
sendto 185.215.193.15 :10000  07 0d 00 02 00 02 00
  send PUBACK

Topic2 recv.
Payload -->publish "ty4tw/topic2" 　<--

And following is the Gateway output for the above test:

20190409 151546.881   SEARCHGW          <---  Client                              03 01 00
20190409 151546.881   GWINFO            --->  Clients                             03 02 01

20190409 151546.881   CONNECT           <---  GatewayTestClient                   17 04 04 01 00 3C 47 61 74 65 77 61 79 54 65 73 74 43 6C 69 65 6E 74
20190409 151547.089   CONNECT           ===>  GatewayTestClient                   10 1D 00 04 4D 51 54 54 04 02 00 3C 00 11 47 61 74 65 77 61 79 54 65 73 74 43 6C 69 65 6E 74
20190409 151547.537   CONNACK           <===  GatewayTestClient                   20 02 00 00
20190409 151547.538   CONNACK           --->  GatewayTestClient                   03 05 00

20190409 151547.538   SUBSCRIBE   0001  <---  GatewayTestClient                   11 12 20 00 01 74 79 34 74 77 2F 74 6F 70 69 63 31

20190409 151547.538   SUBSCRIBE   0002  <---  GatewayTestClient                   11 12 20 00 02 74 79 34 74 77 2F 74 6F 70 69 63 32
20190409 151547.538   SUBSCRIBE   0001  ===>  GatewayTestClient                   82 11 00 01 00 0C 74 79 34 74 77 2F 74 6F 70 69 63 31 01
20190409 151547.538   SUBSCRIBE   0002  ===>  GatewayTestClient                   82 11 00 02 00 0C 74 79 34 74 77 2F 74 6F 70 69 63 32 01
20190409 151547.741   SUBACK      0001  <===  GatewayTestClient                   90 03 00 01 01
20190409 151547.741   SUBACK      0001  --->  GatewayTestClient                   08 13 20 00 01 00 01 00
20190409 151547.904   SUBACK      0002  <===  GatewayTestClient                   90 03 00 02 01
20190409 151547.904   SUBACK      0002  --->  GatewayTestClient                   08 13 20 00 02 00 02 00

20190409 151555.316   PUBLISH     0003  <---  GatewayTestClient                   1F 0C 20 00 02 00 03 70 75 62 6C 69 73 68 20 22 74 79 34 74 77 2F 74 6F 70 69 63 32 22 20 0A
20190409 151555.317   PUBLISH     0003  ===>  GatewayTestClient                   32 28 00 0C 74 79 34 74 77 2F 74 6F 70 69 63 32 00 03 70 75 62 6C 69 73 68 20 22 74 79 34 74 77 2F 74 6F 70 69 63 32 22 20 0A
20190409 151556.520   PUBACK      0003  <===  GatewayTestClient                   40 02 00 03
20190409 151556.521   PUBACK      0003  --->  GatewayTestClient                   07 0D 00 02 00 03 00

20190409 151557.068   PUBLISH     0001  <===  GatewayTestClient                   32 28 00 0C 74 79 34 74 77 2F 74 6F 70 69 63 32 00 01 70 75 62 6C 69 73 68 20 22 74 79 34 74 77 2F 74 6F 70 69 63 32 22 20 0A
20190409 151557.068   PUBLISH     0001  --->  GatewayTestClient                   1F 0C 20 00 02 00 01 70 75 62 6C 69 73 68 20 22 74 79 34 74 77 2F 74 6F 70 69 63 32 22 20 0A
20190409 151557.068   PUBACK      0001  <---  GatewayTestClient                   07 0D 00 02 00 01 00
20190409 151557.068   PUBACK      0001  ===>  GatewayTestClient                   40 02 00 01

20190409 151606.333   UNSUBSCRIBE 0004  <---  GatewayTestClient                   11 14 00 00 04 74 79 34 74 77 2F 74 6F 70 69 63 32
20190409 151606.333   UNSUBACK    0004  --->  GatewayTestClient                   04 15 00 04

20190409 151610.640   PUBLISH     0005  <---  GatewayTestClient                   1F 0C 20 00 02 00 05 70 75 62 6C 69 73 68 20 22 74 79 34 74 77 2F 74 6F 70 69 63 32 22 20 0A
20190409 151610.640   PUBLISH     0005  ===>  GatewayTestClient                   32 28 00 0C 74 79 34 74 77 2F 74 6F 70 69 63 32 00 05 70 75 62 6C 69 73 68 20 22 74 79 34 74 77 2F 74 6F 70 69 63 32 22 20 0A
20190409 151610.790   PUBACK      0005  <===  GatewayTestClient                   40 02 00 05
20190409 151610.790   PUBACK      0005  --->  GatewayTestClient                   07 0D 00 02 00 05 00

20190409 151610.958   PUBLISH     0002  <===  GatewayTestClient                   32 28 00 0C 74 79 34 74 77 2F 74 6F 70 69 63 32 00 02 70 75 62 6C 69 73 68 20 22 74 79 34 74 77 2F 74 6F 70 69 63 32 22 20 0A
20190409 151610.958   PUBLISH     0002  --->  GatewayTestClient                   1F 0C 20 00 02 00 02 70 75 62 6C 69 73 68 20 22 74 79 34 74 77 2F 74 6F 70 69 63 32 22 20 0A
20190409 151610.958   PUBACK      0002  <---  GatewayTestClient                   07 0D 00 02 00 02 00
20190409 151610.958   PUBACK      0002  ===>  GatewayTestClient                   40 02 00 02

When the UNSUBSCRIBE message is sent to the Gateway there are no (TCP) messages sent to the MQTT broker.
I expect that the Gateway forwards the unsubscribe message to the MQTT broker (similarly to the subscribe message). 

I need additional explanation on unsubscribe mechanism.

Thank you in advance.

**Comment by ty4tw** [comment]
Hi aflo1 ,

Thank you for your contribution.
Sorry for the late reply.
I will check it.

**Comment by swadeshee** [comment]
First of ALL, we would like to thank the people responsible for developing the MQTT-SN Gateway.

The same above issue we are also facing in the MQTT-SN gateway code.
Unsubscribe request received by gateway from SNClient but gateway is unable to process and send it to the broker.

**Comment by aflo1** [comment]
Hello,
any news regarding this issue?

Thank you
