### ISSUE TITLE
MQTT-SNGateway connection refused for one client but not another

### ISSUE THREAD

**Issue by jelalanne** [eclipse/paho.mqtt-sn.embedded-c#151]
Hi,
I am using MQTT-SNGateway other Raspberry with radio modules connected by USB cable, with a custom network interface.
When I am not using TLS connection, everything works perfectly with 2 clients. But as soon as I use certificates, only one client is accepted (both client's program are the same, using mqtt-sn-pub binary from 'njh' library). Client1 is sending its data as expected, but Client2 is refused with errno=111.

clients.conf:
Client1,10000@{IPv6ADDR},secureConnection
Client2,10000@{IPv6ADDR},secureConnection

I have tried different ports, and if I invert clients IDs, it's the other that is accepted and the first one rejected. So clearly, problem is coming from GW.

Thanks.

**Comment by ty4tw** [comment]
Hi jelalanne,

Explanation of Client.conf is wrong.  it should be IP address:portNo.
Could you try this ?

Client1,{IPv6ADDR}:10000,secureConnection
Client2,{IPv6ADDR}:10000,secureConnection

**Comment by jelalanne** [comment]
Hi Tomoaki,

Still, it doesn't work. I did:
Client1,fd5a:b03d:7f78::7305:xxxx:xxxx:xxxx:10000,secureConnection
Client2,fd5a:b03d:7f78::efd:xxxx:xxxx:xxxx:10000,secureConnection

Thanks for your time.

________________________________
De : Tomoaki Yamaguchi <notifications@github.com>
Envoyé : vendredi 17 mai 2019 09:45
À : eclipse/paho.mqtt-sn.embedded-c
Cc : jelalanne; Author
Objet : Re: [eclipse/paho.mqtt-sn.embedded-c] MQTT-SNGateway connection refused for one client but not another (#151)


Hi jelalanne,

Explanation of Client.conf is wrong. it should be IP address:portNo.
Could you try this ?

Client1,{IPv6ADDR}:10000,secureConnection
Client2,{IPv6ADDR}:10000,secureConnection

**Comment by jelalanne** [comment]
The thing is, I am using binaries from 'njh' library to publish/subscribe.
From Client2, if I subscribe to a topic and say i'm Client1, it works, even if it's Client2's address in the list...

________________________________
De : Tomoaki Yamaguchi <notifications@github.com>
Envoyé : vendredi 17 mai 2019 09:45
À : eclipse/paho.mqtt-sn.embedded-c
Cc : jelalanne; Author
Objet : Re: [eclipse/paho.mqtt-sn.embedded-c] MQTT-SNGateway connection refused for one client but not another (#151)


Hi jelalanne,

Explanation of Client.conf is wrong. it should be IP address:portNo.
Could you try this ?

Client1,{IPv6ADDR}:10000,secureConnection
Client2,{IPv6ADDR}:10000,secureConnection

**Comment by jelalanne** [comment]
If I only declare Client2, he works. As soon as I declare both, one of them is blocked.

________________________________
De : Tomoaki Yamaguchi <notifications@github.com>
Envoyé : vendredi 17 mai 2019 09:45
À : eclipse/paho.mqtt-sn.embedded-c
Cc : jelalanne; Author
Objet : Re: [eclipse/paho.mqtt-sn.embedded-c] MQTT-SNGateway connection refused for one client but not another (#151)


Hi jelalanne,

Explanation of Client.conf is wrong. it should be IP address:portNo.
Could you try this ?

Client1,{IPv6ADDR}:10000,secureConnection
Client2,{IPv6ADDR}:10000,secureConnection

**Comment by ty4tw** [comment]
Hi,
Could you change the code as follows and try it?
line 95 of linux/udp6/SensorNetwork.cpp    find_first_of() to find_last_of()
````
int SensorNetAddress::setAddress(string* ip_port)
{
	size_t pos = ip_port->find_first_of(":");

	if ( pos == string::npos )
	{
		_portNo = 0;
		_IpAddr = INADDR_NONE;
		return -1;
	}
````
````
int SensorNetAddress::setAddress(string* ip_port)
{
	size_t pos = ip_port->find_last_of(":");

	if ( pos == string::npos )
	{
		_portNo = 0;
		_IpAddr = INADDR_NONE;
		return -1;
	}
````

**Comment by ty4tw** [comment]
Hi,

Try this code.
Line 66 of linux/udp6/SensorNetwork.cpp 
```
/**
 *  convert Text data to SensorNetAddress
 *  @param  buf is pointer of IP_Address:PortNo format text
 *  @return success = 0,  Invalid format = -1
 */
int SensorNetAddress::setAddress(string* data)
{
	const char *cstr = data->c_str();
	if (inet_pton(AF_INET6, cstr, &(_IpAddr.sin6_addr)) == 1 )
	{
		size_t pos = data->find_last_of(":");
		if ( pos != string::npos)
		{
			string port = data->substr(pos + 1);
			int portNo = 0;
			if ( (portNo = atoi(port.c_str())) > 0 )
			{
				_portNo = htons(portNo);
				return 0;
			}
		}
	}
	_portNo = 0;
	memset((void *)&_IpAddr,0,sizeof(_IpAddr));
	return -1;
}
```

**Comment by jelalanne** [comment]
I'm having an error.
Invalid Address    Client1,{IPv6ADDR}:10000,secureConnection
Invalid Address    Client2,{IPv6ADDR}:10000,secureConnection

**Comment by jelalanne** [comment]
It fails there:
if (inet_pton(AF_INET6, cstr, &(_IpAddr.sin6_addr)) == 1 )

**Comment by jelalanne** [comment]
Using your code, const char *cstr contains:
"{IPv6ADDR}:10000,secureConnection"
Is this normal?

**Comment by jelalanne** [comment]
It's ok now, I made now modifications (this below code is not optimized). The thing is that with your code, there was still the portNo and ",secureConnection" in data, so the inet_pton() was not working.
`/**
 *  convert Text data to SensorNetAddress
 *  @param  buf is pointer of IP_Address:PortNo format text
 *  @return success = 0,  Invalid format = -1
 */
int SensorNetAddress::setAddress(string* data)
{
	const char *cstr;
        strncpy(cstr, data->c_str(), data->find_last_of(":"));
	if (inet_pton(AF_INET6, cstr, &(_IpAddr.sin6_addr)) == 1 )
	{
		size_t pos = data->find_last_of(":");
		if ( pos != string::npos)
		{
			string port = data->substr(pos + 1);
			int portNo = 0;
			if ( (portNo = atoi(port.c_str())) > 0 )
			{
				_portNo = htons(portNo);
				return 0;
			}
		}
	}
	_portNo = 0;
	memset((void *)&_IpAddr,0,sizeof(_IpAddr));
	return -1;
}`

**Comment by ty4tw** [comment]
Hi jelalanne ,

Thank you for your contribution.

**Comment by jelalanne** [comment]
Working :) thanks!
I have another 2 small questions, if you have some time.
- With every disconnect ACK I'm having an error. It's still working afterward though.
"Error: BrokerRecvTask can't receive a packet from the broker errno = 0"
- It happens oftenly that when a client sends the connect message, there is small minute of latency before continuing (when it occurs, no clients can't discuss anymore)
