### ISSUE TITLE
Connect failed from RIOT virtual machine

### ISSUE THREAD

**Issue by jhx2002** [eclipse/paho.mqtt-sn.embedded-c#152]
setup:

- virtual network in Ubuntu 18.04

![image](https://user-images.githubusercontent.com/42711262/58411737-90475b00-80a7-11e9-9622-b378a3f88d39.png)

- from Ip6:xxx ping6  Ip6:yyy,   is OK

- from Ip6:yyy ping6  Ip6:xxx,   is OK

- broker and gateway run on host with ip4: 192.168.0.104

- MQTT-SN tools in host ,  pub and sub to gateway is OK

- connect gatway in virtual machine of RIOT ,  FAILED.  The RIOT mqttsn client see  `https://github.com/RIOT-OS/RIOT/tree/master/examples/emcute_mqttsn`

**Comment by jhx2002** [comment]
Test a case, running gateway with ipv6. got error:
```

20190529 181941.706 MQTT-SN/gateway1 has been started.

 ConfigFile: ./gateway.conf
 ClientList: ./clients.conf
 PreDefFile: ./predefinedTopic.conf
 SensorN/W:  UDP Multicast 225.1.1.1:1883 Gateway Port 10000
 Broker:     ::C0A8:0078 : 1883, 8883
 RootCApath: (null)
 RootCAfile: (null)
 CertKey:    (null)
 PrivateKey: (null)



20190529 181943.000   error:getaddrinfo(): Address family for hostname not supported
Error: BrokerSendTask: MQTT-SN/gateway1QoS-1 can't connect to the broker. errno=0 Success 


```

**Comment by ty4tw** [comment]
Hi jhx2002 ,

SensorN/W is not IPV6.    
> SensorN/W:  UDP Multicast 225.1.1.1:1883 Gateway Port 10000

When you set MulticastIP= of gateway.conf to a IPV6 address,  it is shown like     
SensorN/W: Gateway Port: 10000 Broadcast Address: XXXX:XX:-------:XXX::1 Interface: wpan0    

build the gateway for UDP6 with command  'make SENSORNET=udp6'.    
and change the gateway.conf.  then rerun the GW. 
I don't know anything about RIOT. but UDP6 is working on the GW.   
I hope you can make it.

**Comment by jhx2002** [comment]
I rewrite gateway.conf follow your suggestion ,  but still can't  connect. Than you @ty4tw 
```
# SensorNetwork UDP6 config
#GatewayUDP6Bind=fe80::67b8:da5c:8d37:801
GatewayUDP6Bind=fec0:affe::1 
GatewayUDP6Port=10000
GatewayUDP6Broadcast=FF02::1
GatewayUDP6If=tapbr0
```

**Comment by ty4tw** [comment]
It might be a RIOT problem.
What happen if you run the GW on the host, not on the virtual machine?

**Comment by jhx2002** [comment]
I could connect Gateway with other tools running on linux.  Thank you!
