### ISSUE TITLE
Publish on topic from outside the gateway

### ISSUE THREAD

**Issue by jelalanne** [eclipse/paho.mqtt-sn.embedded-c#156]
Hi,
I'm trying to publish a message on a specific topic directly on mosquitto, and I want it to be transfered to the gateway's client which is subscribed to that topic.
My architecture is as followed:
Device <-{Thread network}-> Gateway (uses specific network interface wpan0) <-> TLS mosquitto <-> {other}

I have tried to use mosquitto_pub to publish on the gateway from that {other} segment, but it's not transmited to the Device.

Thanks!

**Comment by ty4tw** [comment]
Attach the GW log.

**Comment by jelalanne** [comment]
Client was not subscribed correctly, closing issue
