### ISSUE TITLE
How to config to use gateway without  broker

### ISSUE THREAD

**Issue by jhx2002** [eclipse/paho.mqtt-sn.embedded-c#159]
How to config to use gateway without  broker

**Comment by mahsan321** [comment]
Gateway is not designed to act standalone. It can only be configured as a gateway to convert UDP traffic to TCP and route it to MQTT Broker.

**Comment by jhx2002** [comment]
can not gateway act as a simple broker ?

**Comment by mahsan321** [comment]
No. It can not. Refer to the Protocol Specifications for more details.

**Comment by jhx2002** [comment]
So how difficult if may be if I modify the gateway to meet my need ?

**Comment by mahsan321** [comment]
What is you trying to do here. I am not following you. Because for that you have a broker than why change the gateway to act as a broker.

**Comment by ty4tw** [comment]
Close this issue because it has not been discussed for a long time.
