### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by balajsra** [eclipse/paho.mqtt-sn.embedded-c#161]
How can I port this to windows?

I would like to use MQTT-SN Tools as the client, this library as the gateway, and Mosquitto as the broker. All of this should work on Windows 10. I have gotten MQTT-SN Tools and Mosquitto to work on Windows, but I am having trouble porting this library to Windows.

I have tried using Cygwin, but it doesn't work.

**Comment by kurukuru8** [comment]
Hi,

Sorry, I have no idea. I don't have any knowledge of Windows. I only know about unix and linux.

**Comment by ty4tw** [comment]
Hi balajsra,
Sorry, I can't help about it.
I have no idea. I do not have any knowlede of Windows.　
I only have a knowlede of unix and linux.

**Comment by balajsra** [comment]
Hi ty4tw,

No worries. I will do my best to port it to windows myself.

If I can get it to work, I'll submit a pull request so you can review it.

Best regards,
balajsra

**Comment by balajsra** [comment]
For those also looking for a windows solution for MQTT-SN client, gateway, and broker, I have found a solution.

* MQTT-SN Client: [MQTT-SN-Tools](https://github.com/njh/mqtt-sn-tools)
* MQTT Broker: [EMQ X Broker](https://github.com/emqx/emqx)
* MQTT-SN Gateway: [EMQX-SN Plugin](https://developer.emqx.io/docs/broker/v3/en/protocol.html#mqtt-sn-protocol)

**Comment by saumilsdk** [comment]
hi @balajsra can you please post commands if you were able to test MQTT-SN gateway using SN Client tools.

**Comment by kevin0598** [comment]
Hello sir, may i ask something, the thing is i use MQTT-SN, arduino and mosquito for my thesis, so can i ask some reference because i don't find any reference about that, can you help me sir?

**Comment by balajsra** [comment]
@saumilsdk I haven't worked on the project that used MQTT in over a year, so I don't remember at this point what the specific commands I used were. I'm pretty sure I just read through the documentation for each of the components I have shared links to and was able to figure it out.

@kevin0598 I haven't worked on the project in around a year, so I don't remember specifics. I can do my best to help you, however. Feel free to send me an email and we can discuss privately.

**Comment by kevin0598** [comment]
Thank you Sir i really appreciate it, Can i ask your private email sir, so i can you some mail

**Comment by balajsra** [comment]
> Thank you Sir i really appreciate it, Can i ask your private email sir, so i can send you some mail

Yes, please email me at balajsra@umich.edu

**Comment by kevin0598** [comment]
Good day Sir i already email you please check it if you have time and sorry
to bother you Sir but i need your help

Pada tanggal Sel, 5 Mei 2020 pukul 10.13 Sravan Balaji <
notifications@github.com> menulis:
