### ISSUE TITLE
Allow forwarder connections over TCP

### ISSUE THREAD

**Issue by chrismgrayftsinc** [eclipse/paho.mqtt-sn.embedded-c#166]
My use case is that I would like to create a data pipeline that reads MQTT-SN packets from a satellite gateway over TCP, wraps them in a forwarder packet with the satellite identifier, sends them to the Paho gateway over TCP, and has the gateway send the decoded MQTT-SN as MQTT to an MQTT broker (and similarly in the other direction).  I would rather use TCP than UDP because the forwarder will live on Kubernetes and UDP does not fit well there.

**Comment by ty4tw** [comment]
Hi 
It's a out of scope of this gateway.
The gateway is for a sensor network not for TCP.
I have no idea about how to implement  TCP sockets as the sensor network.
