### ISSUE TITLE
Gateway client limit.

### ISSUE THREAD

**Issue by mohammedalani-1** [eclipse/paho.mqtt-sn.embedded-c#167]
I have been doing some testing with the mqttsn gateway and I was wondering if I can increase the maximum number of clients (in the MQTTSNGWDefines.h file) without repercussions. Let's say I want to increase the limit of the gateway to 500or 1000 clients, would changing the MAX_CLIENTS definition be enough to achieve that?

**Comment by ty4tw** [comment]
Hi,
Just increase the MAX_CLIENTS is enough.

**Comment by karrthikmohank** [comment]
Hi all,
I have been using the MQTT-SN to MQTT transparent gateway. Like suggested in this post, I  have modified the MAX_CLIENTS to 200 and built the project. I have tried to test the gateway by connecting 130 MQTT-SN clients to it. Still I am unable to connect more than 100 MQTT-SN clients to the gateway. Can you please help me in solving this issue?

Thanks and Regards,
Karthik
