### ISSUE TITLE
MQTT-SN Gateway over ZigBee

### ISSUE THREAD

**Issue by Yamnkelani** [eclipse/paho.mqtt-sn.embedded-c#168]
Hi

I have an issue starting up my MQTT-SN Gateway over ZigBee

I downloaded the paho MQTT-SN gateway and attempted running the gateway over ZigBee. I simply configured the gateway as follows:

```
BrokerName=iot.eclipse.org
BrokerPortNo=1883
BrokerSecurePortNo=8883

ClientAuthentication=NO
AggregatingGateway=NO
QoS-1=NO
Forwarder=NO

PredefinedTopic=NO

GatewayID=1
GatewayName=PahoGateway-01
KeepAlive=900

# XBee
Baudrate=38400
SerialDevice=/dev/ttyUSB0
ApiMode=2

# LOG
ShearedMemory=NO;
```
However, when I run the gateway, I get the following error message 

> terminate called after throwing an instance of 'MQTTSNGW::Exception'
> what(): Can't open the sensor network.

I don't know what I am missing.

**Comment by ty4tw** [comment]
Hi,

iot.eclipse.org was move to mqtt.eclipse.org.
So,  change BrokerName=iot.eclipse.org to BrokerName=mqtt.eclipse.org



2019年11月15日(金) 16:02 Yamnkelani <notifications@github.com>:

**Comment by Yamnkelani** [comment]
Hi .

I changed the broker name. It still throws the error

**Comment by ty4tw** [comment]
Hi,
It might be a setting problem of XBee module.
check the baudrate and API mode are same as gateway.conf.

**Comment by Yamnkelani** [comment]
I got it to work. I changed the "SENSORNET:=udp" to "SENSORNET:=xbee" on the makefile and rebuilt the gateway. Thanks

**Comment by ty4tw** [comment]
Hi,

You don't need to change the Makefile. 
Just enter    make SENSORNET=xbee
