### ISSUE TITLE
Issue when trying to send a publish packet to Mosquitto via MQTT-SN transparent gateway

### ISSUE THREAD

**Issue by chiforbogdan** [eclipse/paho.mqtt-sn.embedded-c#172]
Hello,

I encountered the following error when trying to send a publish message from the pub0sub1 MQTT-SN sample to MQTT-SN broker (which is configured to communicate with a local Mosquitto broker).

 ***************************************************************************
 * MQTT-SN Transparent Gateway
 * Part of Project Paho in Eclipse
 * (http://git.eclipse.org/c/paho/org.eclipse.paho.mqtt-sn.embedded-c.git/)
 *
 * Author : Tomoaki YAMAGUCHI
 * Version: 1.3.1
 ***************************************************************************

20191208 213616.895 PahoGateway-01 has been started.

 ConfigFile: ../gateway.conf
 ClientList: ../clients.conf
 PreDefFile: ../predefinedTopic.conf
 SensorN/W:  UDP Multicast 225.1.1.1:1883 Gateway Port 10000
 Broker:     127.0.0.1 : 1883, 8883
 RootCApath: (null)
 RootCAfile: (null)
 CertKey:    (null)
 PrivateKey: (null)

20191208 213620.334   CONNECT           <---  GatewayTestClient                   16 04 04 01 00 0A 70 75 62 30 73 75 62 31 20 4D 51 54 54 2D 53 4E
20191208 213620.334   CONNECT           ===>  GatewayTestClient                   10 1D 00 04 4D 51 54 54 04 02 00 0A 00 11 47 61 74 65 77 61 79 54 65 73 74 43 6C 69 65 6E 74
20191208 213620.396   CONNACK           <===  GatewayTestClient                   20 02 00 00
Step 3
20191208 213620.396   CONNACK           --->  GatewayTestClient                   03 05 00
Hereee
Error: ClientSendTask can't send a packet to the client GatewayTestClient. Error=22

**Comment by kyberpunk** [comment]
Hi, I've experienced a similar problem and updating the latest gateway.conf from the repository helped me. It seems that _AggregateGateway_ parameter changed to _AggregatingGateway_. After replacing the file with the new one it works fine.

**Comment by ty4tw** [comment]
Closed because there is no answer for a long time.

**Comment by ty4tw** [comment]
Closed because there is no answer for a long time.
