### ISSUE TITLE
How long time will it delay after receive a publish from broker?

### ISSUE THREAD

**Issue by jhx2002** [eclipse/paho.mqtt-sn.embedded-c#174]
How long time will it delay after receive a publish from broker? 
```
I mean t2 - t1 : 
t1 = recv_time of a publish from broker
t2 = send_time to mqtt-sn subscriber 
t3 = recv_time of  mqtt-sn subscriber
```

**Comment by ty4tw** [comment]
Hi,
I have never measured it.
I think it's depends on a hardware which the gateway running on and transaction frequency and capacity.
