### ISSUE TITLE
Not able to execute MQTT-SN-Gateway

### ISSUE THREAD

**Issue by Dinakaranevil** [eclipse/paho.mqtt-sn.embedded-c#179]
terminate called after throwing an instance of 'MQTTSNGW::Exception'
  what():  RingBuffer can't create a shared memory.
Aborted (core dumped)

**Comment by ty4tw** [comment]
Hi,
If you get the error message as follows:
````    
what(): RingBuffer can't create a shared memory.
Aborted (core dumped)
````
You have to start using sudo command only once for the first time.    
````
$ sudo ./MQTT-SNGateway [-f Config file name]
````
I will add the info about this to README.
