### ISSUE TITLE
issue in README.md  in MQTTSN-Gateway 

### ISSUE THREAD

**Issue by Dinakaranevil** [eclipse/paho.mqtt-sn.embedded-c#180]
executable files are not present in the required directory and after make clean build folder gets deleted but our executable after make is present in build folder

**Comment by ty4tw** [comment]
Hi,

I think you used make command with  
**install INSTALL_DIR=directory_name  CONFIG_DIR=directory_name**   arguments.
Related portion of Makefile as follows:
````
INSTALL_DIR=../../
CONFIG_DIR=../../
    .
    .
    .
clean:
	rm -rf $(OUTDIR)

install:
	cp -pf $(PROG) $(INSTALL_DIR)
	cp -pf $(LPROG) $(INSTALL_DIR)
	cp -pf $(CONFIG) $(CONFIG_DIR)
	cp -pf $(CLIENTS) $(CONFIG_DIR)
	cp -pf $(PREDEFTOPIC) $(CONFIG_DIR)
	
````
Nothing seems wrong.
I guess the directory names are incorrect.

**Comment by ty4tw** [comment]
Hi,

Try
```
$ make install
$ ls -l ../../
```
you will find files.
