### ISSUE TITLE
Why use pointer types to compare directly with 0？

### ISSUE THREAD

**Issue by lx121451** [eclipse/paho.mqtt-sn.embedded-c#182]
![image](https://user-images.githubusercontent.com/20105247/74796158-c0ecb600-5302-11ea-87be-d278d6830478.png)

**Comment by ty4tw** [comment]
Hi,
I don't know about the latest C language but are there any problem?

**Comment by ty4tw** [comment]
Hi,
Thank you for your info.
It' should be *gatewayaddress_len.

**Comment by ty4tw** [comment]
This Bug was fixed by Jochen0x90h PR #176.
