### ISSUE TITLE
Add a session recovery mechanism

### ISSUE THREAD

**Issue by lx121451** [eclipse/paho.mqtt-sn.embedded-c#184]
Hello, I tested the characteristics of MQTT-SN under the NBIOT network. As you know, NB is a low-power protocol. When the device enters the sleep state, the core network will release the previous connection, which will cause the device The source data port seen by the gateway will change after waking up. Do you consider adding a session recovery mechanism?

**Comment by ty4tw** [comment]
Hi,
I am not thinking about adding such function.
The device can CONNECT again before sending any message.
