### ISSUE TITLE
Subscribe with QoS not working

### ISSUE THREAD

**Issue by a1lu** [eclipse/paho.mqtt-sn.embedded-c#190]
Hi,
I tried to subscribe a topic with QoS > 0 and publish something into this topic. The result is, The QoS of the received message is only dependent on the QoS of the publisher. AFAIK the QoS level of subscriber and publisher are two different things, like this:
```
PUBLISHER -> qos_pub -> BROKER -> qos_sub -> SUBSCRIBER
```
I used the GatewayTester (run testscript including step 1) to make some logs.
Test 1:
 *  `subscribePredefTopic1()` subscribes with QoS1
*  `publishTopic1` publishes with QoS0
[test1_gatewaytester.txt](https://github.com/eclipse/paho.mqtt-sn.embedded-c/files/4430989/test1.txt)
[qos0_gateway.txt](https://github.com/eclipse/paho.mqtt-sn.embedded-c/files/4430983/qos0.txt)

Test 2:
 *  `subscribePredefTopic1()` subscribes with QoS1
*  `publishTopic1` publishes with QoS1
[test2_gatewaytester.txt](https://github.com/eclipse/paho.mqtt-sn.embedded-c/files/4430990/test2.txt)
[qos1_gateway.txt](https://github.com/eclipse/paho.mqtt-sn.embedded-c/files/4430984/qos1.txt)

I would expect a PUBACK from the receiver like in Test2 also in Test1.

Best regards

**Comment by ty4tw** [comment]
Hi a1lu,
You can't expect PUBACK.  
It's a spec of MQTT. 

According to the specification [MQTT-3.8.4-6],
>The Server might grant a lower maximum QoS than the subscriber requested. The QoS of Payload Messages sent in response to a Subscription MUST be the minimum of the QoS of the originally published message and the maximum QoS granted by the Server.

**Comment by a1lu** [comment]
Ah, too bad. Thanks anyway.
