### ISSUE TITLE
Gateway doesn't support clients with certificates for AWS IOT endpoint

### ISSUE THREAD

**Issue by saumilsdk** [eclipse/paho.mqtt-sn.embedded-c#199]
I have couple of  IOT devices which are registered as AWS IOT device and have a certificate to communicate to AWS IOT using MQTT protocol. 
Now i wanted to use MQTT-SN gateway in middle so that IOT devices can use UDP connection.
Issue is where we cannot provide each client with their specific certificates and certificate has to be given at MQTT-SN gateway.conf. This makes all clients communication to AWS IOT as single principleID.

**Comment by ty4tw** [comment]
Hi,
>This makes all clients communication to AWS IoT as single 

Clients defined as secure by the clients.conf file can commutate to AWS IoT.

**Comment by saumilsdk** [comment]
Hi @ty4tw . I have clients which are having their own certificates generated by AWS IOT at the time of registration. If i have MQTT-SN gateway as intermediary client, then i'll see only one client connecting to AWS IOT even if i have many clients connecting to gateway.

**Comment by ty4tw** [comment]
The gateway can not use client certification.
So use core certification instead of them.

**Comment by saumilsdk** [comment]
@ty4tw What is the core certification? How will I identify individual clients on AWS IOT then? Even if MQTT-SN is acting as transparent, i can see only one client which is gateway connected at broker.

**Comment by ty4tw** [comment]
Hi,
When ClientAuthentication=YES in gateway.conf, Only clients which exist in
clients.conf can CONNECT the gateway.
I think AWS IoT allows sharing  a TLS certification for a device group.
So, All clients can share the gateway's certification.

Tomoaki  YAMAGUCHI

2020年5月21日(木) 15:53 Saumil Kapadia <notifications@github.com>:

**Comment by nikhil1983** [comment]
Hello @ty4tw ,
I currently have few mqtt-sn clients communicating with Eclipse paho mqtt-sn gateway and everything works fine. I am able to use public brokers for ex Eclipse IoT broker or local broker running on PC. 

Now I want to establish connection from MQTT-SN gateway to AWS MQTT broker. So will providing path of my root ca certificate and private keys along with clients list solve the issue ?

And in the sample client list I can see the clients are mentioned as client name,ipaddr,extra information.
Currently all my mqtt-sn all are connecting with same IP addr with different client names. 
So can the below information enough for my clients file ?
Client1,ipv4addr
Client2,ipv4ddr

What else information I have to add to establish a connection to AWS IoT

**Comment by nikhil1983** [comment]
@saumilsdk did you get it working ? Because I am also stuck in same situation like yours. Any suggestion will be helpful

**Comment by saumilsdk** [comment]
@nikhil1983 i had it working for AWS IOT. Below is the configuration I had used.

`
![image](https://user-images.githubusercontent.com/8816702/129241501-b01f4c97-8e0f-4d3a-97c7-bb94033f60ce.png)

`

**Comment by nikhil1983** [comment]
Hey Saumil,

Thanks brother. As you have enabled the authentication on can you just also
show me your clients file.

I am currently finding it difficult in defining my clients in client list
as I don't know which IP address and port I should mention in it along with
client ID.

**Comment by saumilsdk** [comment]
@nikhil1983 I would recommend to change code and support any client to connect to gateway with ClientAuthentication=NO and still connect to AWS IOT using secure connection ignoring this value in code.

My clients conf when ClientAuthentication=YES.

```
# Each client should have unique IP and PORT.
# Random IP and PORT combination seems working but has to be unique.
# AS Broker's Connection is SSL, write "secureConnection".

GatewayTestClient,127.0.0.1:20020,secureConnection
client1,35.170.7.1:20020,secureConnection
client2,35.170.7.2:20020,secureConnection
client3,35.170.7.3:20020,secureConnection
 ```

**Comment by nikhil1983** [comment]
Hey,

Thanks for the clients file.

I see that in comment section you have written we have to use different IP
address for each client's. Do you know the reason for that ?

You advised me to change code so that I can use disable authentication and
still connect. I would like to know which code you were talking about. Paho
mqqt-sn gateway side ?


And finally in paho-mqttsn-gateway config file you passed certificates and
keys for authentication. Are this device certificate ?

**Comment by saumilsdk** [comment]
@nikhil1983 While using `ClientAuthentication=YES` all clients has to have `secureConnection` in clients list.

**Comment by nikhil30081995** [comment]
@saumilsdk Whenever i use **ClientAuthentication=YES** my MQTT-SN
 clients are not able to find MQTT-SN gateway. And when i just switch off the ClientAuthentication=NO and just pass certificates than my MQTT-SN clients are able to find gateway but can't connect to it.

**Comment by adarsht88** [comment]
@saumilsdk @nikhil30081995 @nikhil1983 

In gateway.config file you have passed cert and key files, I have multiple thing or device, how can I pass these multiple certs.
if we have to generate group certificate let me know how to do that.

thank you.
