### ISSUE TITLE
Can i run this on Windows?

### ISSUE THREAD

**Issue by kevin0598** [eclipse/paho.mqtt-sn.embedded-c#200]
I want to use Windows for my OS can i run it at Windows and Can i use MS Visual Code for my text editor??

**Comment by kevin0598** [comment]
I already tried using Cygwin,and when i try to

$ make [SENSORNET={udp6|xbee}]

then this error came up,is there something wrong with the file?? because from what i know Cygwin can make we work on Linux environment

![image](https://user-images.githubusercontent.com/48360957/81282876-5be96680-908e-11ea-8184-d9431e552be7.png)

**Comment by ty4tw** [comment]
Hi,
Exec  make without argument.  

By default, a gateway for UDP is built.
In order to create a gateway for UDP6 or XBee, SENSORNET argument is required.

**Comment by kevin0598** [comment]
Hi

What Argument should i put here?
 i just follow your instruction in the README

**Comment by kevin0598** [comment]
Ow Sorry i already tried

$ make SENSORNET=udpp6 

but still came out that error,so what should i do?

**Comment by ty4tw** [comment]
Hi,
Error messages say some include files are missing.
Does anyone can help this issue I don’t know about Cygwin environment?

**Comment by ty4tw** [comment]
Hi,
master and develop are current existing branches as you said.
Try develop branch and if you can’t build it, it must be a problem of Cygwin build environment.
I’ve never tried Cygwin environment before. It’s out of my scope.

**Comment by kevin0598** [comment]
Hi

Thank you for answering

i already use Linux at Virtual Box but it seem the gateway can't publish from mqtt-sn client to mqtt broker but for the mqtt-sn client i can do sub and pub

are this gateway support for mosquitto broker? because the broker doesn't get any message from the mqtt-sn client pub
![image](https://user-images.githubusercontent.com/48360957/81366454-4d965b80-911d-11ea-8cd5-b3c4de8458ea.png)

and this is the prove that there is no error for mqtt-sn client pub/sub

pub as mqtt-sn client
![image](https://user-images.githubusercontent.com/48360957/81366512-71f23800-911d-11ea-9403-334008887e34.png)


sub as mqtt-sn client
![image](https://user-images.githubusercontent.com/48360957/81366488-6272ef00-911d-11ea-89a4-8bf93fd18499.png)

**Comment by ty4tw** [comment]
Hi
Can I see the log of gateway?

**Comment by kevin0598** [comment]
i have found some error like this,is this the problem?
![image](https://user-images.githubusercontent.com/48360957/81367355-97804100-911f-11ea-90e5-abf5dcbbb474.png)

is this right? for the log
![image](https://user-images.githubusercontent.com/48360957/81367458-e29a5400-911f-11ea-85b9-6e6aa1893b22.png)

**Comment by ty4tw** [comment]
It works fine.   
====> and <==== arrow mean message to/from the broker.
——> and <—— arrows mean message to/from clients.

**Comment by kevin0598** [comment]
Hi

But why is my broker that use mosquitto doesn't receive any data that i send from mqtt-sn client even though at the mqtt-sn gateway it said success to send data?? Is there a problem with my broker? Or this gateway doesn't support mosquitto broker??

And i can said that my mqtt-sn client and my mqtt-sn gateway is  success right??

**Comment by ty4tw** [comment]
Did you change gateway.conf to set your own broker?

**Comment by kevin0598** [comment]
What should i change sir?

I'm new here and I need some guidance
![image](https://user-images.githubusercontent.com/48360957/81375338-e33ce580-9133-11ea-99d6-ceacf0ed3007.png)

and here is the error on the gateway
![image](https://user-images.githubusercontent.com/48360957/81375356-ed5ee400-9133-11ea-8389-662881bcfa2a.png)

**Comment by kevin0598** [comment]
gateway.conf have a broker name,if i use mosquitto broker then what should i name it? or mqttcloud?

**Comment by ty4tw** [comment]
Write IP address and portNo instead of the host name.

**Comment by kevin0598** [comment]
Yeah it worked

Now last question, is this library i can implemented it on Arduino nano that using NRF24L01 as the gateway?

**Comment by ty4tw** [comment]
If you can run Linux os on those machine answer is yes.

**Comment by kevin0598** [comment]
thank you sir i will try it
