### ISSUE TITLE
Can i add RF network at this Gateway? 

### ISSUE THREAD

**Issue by kevin0598** [eclipse/paho.mqtt-sn.embedded-c#201]
I want to use arduino nano + NRF24L01 as a MQTT-SN client just like this git https://github.com/bittailor/BtMqttSn

And then this git as my gateway, but there is some problem because i use RF network and in this git just have Xbee and UDP network, so can i add RF network to this gateway? If i can, then what should i do? And what should i changer or add??

**Comment by ty4tw** [comment]
Just implement SensorNetAddress and  SensorNetwork classes in src/Linux/NRF24L01 directory as same as src/Linux/udp/SensorNetwork.cpp and SensorNetwork.h.

**Comment by kevin0598** [comment]
So i just create new Folder for src/Linux/NRF24L01 and copy SensorNetwork.cpp and SensorNetwork.h from src/Linux/udp,is that right? 

Then what should i do so this gateway can run RF network or i mean what should i change in that file so this gateway can recognize RF Network?? I'm new for this please help me Sir

thank You Sir

**Comment by ty4tw** [comment]
Implement SensorNetworkAddress and SensorNetwork classes for your network
devise by yourself.

2020年5月9日(土) 23:18 Kevin <notifications@github.com>:

**Comment by kevin0598** [comment]
Okay Sir Thank you
