### ISSUE TITLE
Gateway hungs on enabling QOS-1-YES

### ISSUE THREAD

**Issue by saumilsdk** [eclipse/paho.mqtt-sn.embedded-c#204]
I have mqtt-sn gateway connecting to AWS IOT broker using client certificates. I have enabled QoS-1=YES in the gateway.conf file for MQTT-SN. 

After that gateway doesn't connect to AWS IOT broker and hungs on any packet receveid.

**Comment by ty4tw** [comment]
Hi,

Did you write your client in a clients.conf file. Other wise QOS-1 client is not authorized.
So, all packets from the unauthorized client are ignored.

**Comment by saumilsdk** [comment]
Yes you are right.
