### ISSUE TITLE
Use unsigned data type in MQTTSNLenString

### ISSUE THREAD

**Issue by a1lu** [eclipse/paho.mqtt-sn.embedded-c#206]
Hi,
I got the following warning:

```
MQTTSNSerializePublish.c: In function 'MQTTSNSerialize_register':
MQTTSNSerializePublish.c:235:70: warning: signed and unsigned type in conditional expression [-Wsign-compare]
     topicnamelen = (topicname->cstring) ? strlen(topicname->cstring) : topicname->lenstring.len;
```

The struct [MQTTSNLenStrings `len` member](https://github.com/eclipse/paho.mqtt-sn.embedded-c/blob/ad86a276b56253f39686bc0a5984b4ebf39fe36f/MQTTSNPacket/src/MQTTSNPacket.h#L111) is an signed int but is compared to `strlen`s `size_t` return value.

The `len` member is written only in https://github.com/eclipse/paho.mqtt-sn.embedded-c/blob/ad86a276b56253f39686bc0a5984b4ebf39fe36f/MQTTSNPacket/src/MQTTSNPacket.c#L214

This would not work if `len` is unsized, but this could be changed to something like 

```
    if (enddata > *pptr)
    {
        MQTTSNString->lenstring.len = enddata - *pptr;
        MQTTSNString->lenstring.data = (char*)*pptr;
        *pptr += MQTTSNString->lenstring.len;
    }
    else
    {
        MQTTSNString->lenstring.data = NULL;
        MQTTSNString->cstring = NULL;
        MQTTSNString->lenstring.len = 0
    }
```

Regards

**Comment by ty4tw** [comment]
Hi,
 This will be fixed as follows:
topicnamelen = (topicname->cstring) ? (int)strlen(topicname->cstring) : topicname->lenstring.len;
