### ISSUE TITLE
[Question] How to configure a forwarder?

### ISSUE THREAD

**Issue by alexiordan** [eclipse/paho.mqtt-sn.embedded-c#208]
Hi everyone,
First of all thank you for doing a great supporting this!
My scenario is as follows:
Arduino with XBeeModule <---> Raspberry with XBeeModule and GSM Module <--> Cloud
I intend to: MQTT-SNPub/Sub (Arduino) <---> MQTT-SNForwarder (RaspberryPi) <----> MQTT-SNGateway - Mosquitto (Cloud), so to switch over from ZigBee to UDP and the other way around.
1. Is it feasible?
2. How should I approach the Forwarder part? I've attempted to FORWARDER=YES in gateway.config, but without luck.

For the record I was able to exchange messages like this: MQTT-SNPub/Sub <---> MQTT-SNGateway <----> Mosquitto <---> mosquitto_pub/sub.

Thank you,
Alex

**Comment by ty4tw** [comment]
Gateway can send and recieve encapsulated packets, when FORWARDER=YES in gateway.conf.
Clients<-->Forwarder<--[encapsulated]-->GW<--->Broker
Forwarder is not included in this repo.
