### ISSUE TITLE
Aggregater Gw is not fully done ?

### ISSUE THREAD

**Issue by aymanalzubair** [eclipse/paho.mqtt-sn.embedded-c#215]
Hi, 
thank you for your great work ..
when I tried the aggregate Gw .. I noticed that multiple bugs and issues during the operation .. could I assume that Aggregater is not fully final compared with the transparent type ?

**Comment by ty4tw** [comment]
Hi,
It should work.
Could you inform me what bugs occurred ?  I will check those.
