### ISSUE TITLE
Suspicious code in MQTTSNGWPacket.cpp

### ISSUE THREAD

**Issue by osaether** [eclipse/paho.mqtt-sn.embedded-c#219]
Setting buf to _buf in this function in MQTTSNGWPacket.cpp has no effect:

```
int MQTTSNPacket::serialize(uint8_t* buf)
{
	buf = _buf;
	return _bufLen;
}
```

**Comment by ty4tw** [comment]
Hi,
Serialize method returns serialized data and it’s length.
it’s not suspicious code.

**Comment by osaether** [comment]
> Hi,
> Serialize method returns serialized data and it’s length.
> it’s not suspicious code.

You are setting the local pointer "buf" to "_buf" but "buf" is not returned from the function. If you want to change what "buf" points to you must use "*buf."

**Comment by ty4tw** [comment]
int MQTTSNPacket::serialize(uint8_t* buf)  is a getter method, not a setter method.
