### ISSUE TITLE
Gateway: some warnings on build on Ubuntu

### ISSUE THREAD

**Issue by icraggs** [eclipse/paho.mqtt-sn.embedded-c#22]
MQTTSNGateway/src/linux/Timer.cpp: In member function ‘void MQTTSNGW::LightIndicator::lit(int, const char_)’:
MQTTSNGateway/src/linux/Timer.cpp:187:33: warning: ignoring return value of ‘ssize_t write(int, const void_, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
   write(_gpio[gpioNo], onoff, 1);
                                 ^
MQTTSNGateway/src/linux/Timer.cpp: In member function ‘void MQTTSNGW::LightIndicator::pinMode(int)’:
MQTTSNGateway/src/linux/Timer.cpp:200:27: warning: ignoring return value of ‘ssize_t write(int, const void_, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
  write(fd, no, strlen(no));
                           ^
MQTTSNGateway/src/linux/Timer.cpp:211:20: warning: ignoring return value of ‘ssize_t write(int, const void_, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
  write(fd,"out", 3);

**Comment by ty4tw** [comment]
Ian,

return value of write() is useless in this case. 
when the return value indicates a error, it can not be recovered.
so, let it be.
      
![compilelog](https://cloud.githubusercontent.com/assets/7830788/17543435/98838dcc-5f0b-11e6-9adb-f0be65ff475e.png)


![lightindicatorwarning](https://cloud.githubusercontent.com/assets/7830788/17543286/6df59dc6-5f0a-11e6-918e-9b2d2e13cae7.png)

**Comment by ty4tw** [comment]
I updated codes.  https://github.com/eclipse/paho.mqtt-sn.embedded-c/pull/32/commits/93df7db12e889018a542522f9eff2f492e47ef68
```
void LightIndicator::pinMode(int gpioNo)
{
	int rc = 0;
	int fd = rc; // eliminate unused warnning of compiler
```
Now, you can close this Issue after marge #31.

**Comment by ty4tw** [comment]
Hi Ian,
Please close this issue.
