### ISSUE TITLE
Need support for DTLS for secured communication

### ISSUE THREAD

**Issue by saumilsdk** [eclipse/paho.mqtt-sn.embedded-c#224]
Need support for DTLS for secured communication between clients and gateway. Please let me know how to achieve that.

**Comment by icraggs** [comment]
Hello.  I've not yet met anyone who has successfully implemented DTLS.  I know some people who have started looking but then found it would be a substantial amount of work, so got no further than that.

Given the likely low number of people who have experience in this area, and I'm not one of them at this time, I don't think you are likely to be able to get support without paying for it.

**Comment by mailych** [comment]
Hi @icraggs ,
I am thinking of using tinydtls https://github.com/eclipse/tinydtls and its API's to bring DTLS support to mqtt-sn.
Do you think, that would reduce significant amount of work required to bring DTLS support?
Thanks in advance.
