### ISSUE TITLE
TLS hostname bypass

### ISSUE THREAD

**Issue by saumilsdk** [eclipse/paho.mqtt-sn.embedded-c#233]
I am using MQTT-SN to connect to secured broker using TLS certificates. But server currently doesn't have certificate with its hostname as SN. Is there a way to bypass/ignore below check?

`SSL_get_peer_certificate() error: Broker awsmblxXXX dosen't match the host name localhost`

**Comment by ty4tw** [comment]
Hi,

It’s impossible as far as I know.

**Comment by saumilsdk** [comment]
@ty4tw   Can you please add config support to skip it with a boolean config "enabledHostVerification=true" by default?

**Comment by ty4tw** [comment]
Hi,
Skipping the server certificate procedure is for a temporally debug.
A permanent solution is using a local host certificate.
