### ISSUE TITLE
Gateway: DTLS with PSK support

### ISSUE THREAD

**Issue by sonny82** [eclipse/paho.mqtt-sn.embedded-c#244]
Hi, 

I can see that support for DTLS has been added recently but it is not yet merged into master.
I would like to know if PSK mode is also supported or only cert mode?
In the gateway.conf I can only find configuration for cert mode (settings DtlsCertsKey, DtlsPrivKey).

Thank you and best regards,
Marcel

**Comment by ty4tw** [comment]
Hi Sonny82,
Gateway doesn’t support PSK.

**Comment by sonny82** [comment]
Ok, thank you for the info.
