### ISSUE TITLE
MQTT-SN Forwarder

### ISSUE THREAD

**Issue by remay** [eclipse/paho.mqtt-sn.embedded-c#27]
Has anyone considered implementing a MQTT-SN Forwarder?

I have a desire to be able to implement the following:

MQTT-SN Client <--2.4GHz packet radio transport--> MQTT-SN Forwarder <--serial transport--> MQTT-SN Gateway <--IP transport--> MQTT Broker

So I'm looking for a forwarder with plugable transport on each side.   I'm open to pointer elsewhere, or, if welcome here, I might start looking at creating one based on the existing code here for contribution back?

Rob.

**Comment by icraggs** [comment]
We've considered it, yes.  But haven't got around to creating one yet.  I don't know of one that's pluggable, or any one right now that I remember.  We would welcome a contribution of one, based on the existing code here preferably, for ease of maintenance.  The MQTTSNPacket library as a minimum

**Comment by MichalFoksa** [comment]
I thought about adding MQTT-SN Forwarder encapsulation into the MQTT-SN Gateway (Mqtt-SN packets are encapsulated according to chapter 5.5 Forwarder Encapsulation in MQTT-SN Protocol Specification v1.2.).

Packet flow would be following:
````
#  Component
1. Node - node speaks MQTT-SN protocol
    <-- MQTT-SN packet over radio/light/smoke/ether/... transport-->
2.         MQTT-SN Forwarder
            <--IP transport (encapsulated MQTT-SN packet) -->
3.                 MQTT-SN Gateway
                    <--IP transport (MQTT packet)--> 
4.                        MQTT Broker
````

Cons:
- one MQTT-SN Forwarder (component number 2) can serve multiple nodes
- one MQTT-SN Gateway can serve mix of multiple MQTT-SN Forwarders and UDP capable MQTT-SN clients.
- MQTT-SN Forwarder does not have to be on the same box as MQTT-SN Gateway

MQTT-SN Forwarder would be custom made to extract MQTT-SN packet from whatever radio/light/smoke protocol and encapsulated it into "Forwarder Encapsulation" packet.

I added encapsulation into RSMB before. Should not be that difficult, once I get oriented in this gateway.

Does this fit into your view and Is there an interest to add forwarder encapsulation into the MQTT-SN Gateway?

Michal
