### ISSUE TITLE
How to run MQTTSNClient?

### ISSUE THREAD

**Issue by Greblys** [eclipse/paho.mqtt-sn.embedded-c#28]
Could you, please, provide a sample with main where we could see how to use MQTTSNClient API?

**Comment by icraggs** [comment]
Unfortunately I haven't finished the high level API yet.  I started but left it unfinished, so for the time being I use MQTTSNPacket.  Now that Tomoaki has contributed an MQTT-SN gateway, I do have an incentive to get on and finish it.
