### ISSUE TITLE
MQTT-SN to MQTT embedded transparent gateway

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt-sn.embedded-c#3]
migrated from Bugzilla [#444079](https://bugs.eclipse.org/bugs/show_bug.cgi?id=444079)
status NEW severity _enhancement_ in component _MQTT-SN Embedded C/C++_ for _---_
Reported in version _unspecified_ on platform _PC_
Assigned to: Al Stockdill-Mander

On 2014-09-15 06:32:52 -0400, Ian Craggs wrote:

> Now we have an MQTT-SN embedded client, it would be good to have an MQTT-SN to MQTT transparent gateway using the embedded clients.  It should allow any MQTT-SN transport to be used - UDP, ZigBee, serial, for instance, and in the same way as the other higher level embedded code:
> 
> 1) not use any system libraries, unless they are pluggable
> 2) not use any dynamic memory allocation
> 3) use C++ at least to start with

**Comment by ty4tw** [comment]
This repository is for C  not C++.  so, I tried to change it to C++.  but it seems like only commiters can do it.   can you change it to C++ project.
then I will make a pull request of a MQTT-SN Gateway.
other wise, they can not compile with Eclipse simply.

**Comment by ty4tw** [comment]
How to change.

add the one line to .project file.  and set properties of C++ compiler then rebuild the project.

<nature>org.eclipse.cdt.core.ccnature</nature> into <natures></natures> as follows:

	<natures>
		<nature>org.eclipse.cdt.core.cnature</nature>
		<nature>org.eclipse.cdt.core.ccnature</nature>
		<nature>org.eclipse.cdt.managedbuilder.core.managedBuildNature</nature>
		<nature>org.eclipse.cdt.managedbuilder.core.ScannerConfigNature</nature>
	</natures>

**Comment by icraggs** [comment]
First contribution from Tomoaki has been approved and merged.

**Comment by icraggs** [comment]
Tomoaki's gateway is up and running!
