### ISSUE TITLE
DISCONNECT handling

### ISSUE THREAD

**Issue by ty4tw** [eclipse/paho.mqtt-sn.embedded-c#31]
Paul Kierstead  wrote,
So, I tweaked TLS_client_method to be TLSv1_2_client_method and it compiles fine on the PI (but I presume this limits it to TLS1.2, which is fine by me...) and it #29 is working quite well on the PI. My previous complaints are all nicely addressed :)

Here is one thing that is sort of I think is only hinted at by the standard, which I implemented in previous gateway, but seems "open". Let say I power-cycle/etc the gateway. Now, the client keeps on going ... and sends a publish. The gateway ignores the client: "Not an active client". It would be really useful if the gateway sent back a DISCONNECT so that the client could immediately re-establish the connection.  Otherwise, a client sending QoS 0 messages doesn't know it is no longer connected and all the messages go to /dev/null. I think this is an oversight in the standard (or I've missed it.... I might have even known when I implemented  a gateway, but that was quite a while ago). Without it, QoS 0 is almost useless.

**Comment by ty4tw** [comment]
Hi Paul,
 According to the specification of MQTT broker never sends DISCONNECT message.  
but, according to the specification of MQTT-SN;

As with MQTT, the DISCONNECT message is sent by a client to indicate that it wants to close the connection.The gateway will acknowledge the receipt of that message by returning a DISCONNECT to the client. A server or gateway may also sends a DISCONNECT to a client, e.g. in case a gateway, due to an error, **cannot map a received message to a client**.   

so, I think  it's not a problem to send DISCONNECT from the gateway.

1) Gateway send DISCONNECT message to a client and broker when the client doesn't send any message within  the keep alive time.
2) Gateway send DISCONNECT message to a client when the gateway can not send message to the broker. (Gateway requires the client to send CONNECT to establish a connection between the broker.)

> said

t

**Comment by ty4tw** [comment]
paulkierstead@gmail.com wrote:

When the gateway gets unknown client publish, it still doesn't send a DISCONNECT:
 ***************************************************************************
 * MQTT-SN Transparent Gateway
 * Part of Project Paho in Eclipse
 * (http://git.eclipse.org/c/paho/org.eclipse.paho.mqtt-sn.embedded-c.git/)
 *
 * Author : Tomoaki YAMAGUCHI
 * Version: 0.8.0
 ***************************************************************************
20161004 135202.607 PahoGateway-01 has been started.
 ConfigFile:  ./gateway.conf
 SensorN/W:   API mode 1, Baudrate 9600, SerialDevice /dev/ttyUSB1
 Broker:      localhost : 1883, 8883
 RootCApath:  (null)
 RootCAfile:  (null)
 ClientCerts: (null)

20161004 135203.304   PUBLISH     0000  <---  Non Active Client !                 0C 00 00 02 00 00 38
20161004 135218.302   PUBLISH     0000  <---  Non Active Client !                 0C 00 00 02 00 00 39
20161004 135233.298   PUBLISH     0000  <---  Non Active Client !                 0C 00 00 02 00 00 30
20161004 135248.293   PUBLISH     0000  <---  Non Active Client !                 0C 00 00 02 00 00 31

 This happens when you cycle the gateway with a client connected. Unless the client tries a PING or a >QoS0 publish, it will never figure out it is disconnected. I think the gateway should send back a DISCONNECT in this circumstance, as it is essentially the only way to recover.

**Comment by PaulKierstead** [comment]
The latest push does now send a disconnect, but with an xbee at least, it crashes:
20161006 021642.527   PUBLISH     0000  <---  Non Active Client !                 0C 00 00 02 00 00 39
20161006 021642.581   DISCONNECT        --->  Non Active Client !                 18
*** Error in `Build/MQTT-SNGateway': free(): invalid pointer: 0x01fd1289 ***
./run_gateway: line 1: 10409 Aborted                 Build/MQTT-SNGateway -f gateway.conf

Let me know if you need more info.

**Comment by ty4tw** [comment]
Cause is Creation of SensorNetAddress.
I  fixed it.

**Comment by PaulKierstead** [comment]
Unfortunately, something crept in when building for xbee. 
~~~~
MQTTSNGateway/src/MQTTSNGWClientRecvTask.cpp:134:58: error: ‘class MQTTSNGW::SensorNetAddress’ has no member named ‘getIpAddress’
     addr->setAddress(_sensorNetwork->getSenderAddress()->getIpAddress(), _sensorNetwork->getSenderAddress()->getPortNo());
                                                          ^
MQTTSNGateway/src/MQTTSNGWClientRecvTask.cpp:134:110: error: ‘class MQTTSNGW::SensorNetAddress’ has no member named ‘getPortNo’
     addr->setAddress(_sensorNetwork->getSenderAddress()->getIpAddress(), _sensorNetwork->getSenderAddress()->getPortNo());
~~~~

**Comment by ty4tw** [comment]
Fixed by means of  using operator = .   and committed.

**Comment by PaulKierstead** [comment]
You're working late! Thank you very much, for the fast response and great work. Works great now, the disconnect lets the node know to reconnect!
~~~~

 ***************************************************************************
 * MQTT-SN Transparent Gateway
 * Part of Project Paho in Eclipse
 * (http://git.eclipse.org/c/paho/org.eclipse.paho.mqtt-sn.embedded-c.git/)
 *
 * Author : Tomoaki YAMAGUCHI
 * Version: 0.9.0
 ***************************************************************************

20161006 151838.221 PahoGateway-01 has been started.

 ConfigFile:  ./gateway.conf
 SensorN/W:   API mode 1, Baudrate 9600, SerialDevice /dev/ttyUSB1
 Broker:      localhost : 1883, 8883
 RootCApath:  (null)
 RootCAfile:  (null)
 ClientCerts: (null)

20161006 151844.785   PUBLISH     0000  <---  Non Active Client !                 0C 00 00 02 00 00 38
20161006 151844.839   DISCONNECT        --->  Non Active Client !                 18

20161006 151844.922   CONNECT           <---  SomeClientID                        04 0C 01 00 3C 53 6F 6D 65 43 6C 69 65 6E 74 49 44
     PacketHandleTask gets CONNECT      from the client.
20161006 151844.976   WILLTOPICREQ      --->  SomeClientID                        06
20161006 151845.062   WILLTOPIC         <---  SomeClientID                        07 10 6D 71 74 74 73 6E 74 65 73 74 2F 73 74 61 74 75 73
     PacketHandleTask gets WILLTOPIC      from the client.
20161006 151845.119   WILLMSGREQ        --->  SomeClientID                        08
20161006 151845.168   WILLMSG           <---  SomeClientID                        09 30
     PacketHandleTask gets WILLMSG      from the client.
20161006 151845.191   CONNECT           --->  SomeClientID                        10 2E 00 04 4D 51 54 54 04 26 00 3C 00 0C 53 6F 6D 65 43 6C 69 65 6E 74 49 44 00 11 6D 71 74 74 73 6E 74 65 73 74 2F 73 74 61 74 75 73 00 01 30
20161006 151845.193   CONNACK           <---  SomeClientID                        20 02 00 00
     PacketHandleTask gets CONNACK      from the broker.
20161006 151845.248   CONNACK           --->  SomeClientID                        05 00

~~~~
