### ISSUE TITLE
MQTT-SN Gateway does not support QoS -1.

### ISSUE THREAD

**Issue by PaulKierstead** [eclipse/paho.mqtt-sn.embedded-c#34]
If you send a message with QoS -1, the gateway treats you like a bad client:

```
20161012 040143.368   PUBLISH     0000  <---  Non Active Client !                 0C 62 58 31 00 00 41

===> Send:     7e 00 10 10 01 00 13 a2 00 40 f1 6e b5 4a 81 00 00
     Payload:  02 18   checksum   00
 7e
===> Recv:     00 07 8b 01 4a 81 24 00 00 84    checksum ok
20161012 040143.455   DISCONNECT        --->  Non Active Client !                 18
```

Note here i have used a short topic; the packet library also seems to support some non-standard (1.2 standard..) inline topic name using a "normal" topic, while the 1.2 standard says only short and pre-defined topics are support. It would be nice to support the library normal topic method as well to allow longer topics in QoS -1

**Comment by ty4tw** [comment]
It would be nice, but QoS-1 is out of scope.  only QoS 0, 1, 2.

**Comment by PaulKierstead** [comment]
Perhaps I'll add it then in  my own fork. It is actually extremely useful for ultra low power devices that don't need to chit chat and only wake for extremely short period of times, like motion sensors, etc. It shouldn't be hard to do; you just need to keep open a connection to the broker and forward all the -1 publish requests over it at QoS 0. Full MQTTSN is actually still pretty big, and a lot of messages if you want to only run a device for milliseconds at a time in extremely small memory footprint.

**Comment by PaulKierstead** [comment]
Hmm, maybe I'll explore just using very long duration with no subscriptions (so technically can go to sleep as the gateway shouldn't be sending anything much). In theory then one can just fire off a single QoS 0 packet once in a while, though the best this can do is 18 hours.

**Comment by ty4tw** [comment]
> you just need to keep open a connection to the broker
It's not so easy as you thought. 

If QoS -1 is needed, the best way is to design a new Gateway which has only function to handle QoS -1 PUBLISH message.  
GWINFO, ADVERTISE, PINGRESP, WILLTOPICREQ, REGISTER, SUBSCRIBE and UNSUBSCRIBE, PUBACK etc,  are not necessary.  This makes Gateway simple and easier.

**Comment by PaulKierstead** [comment]
But then I would have to operate two gateways, with multiple radios; that is seriously suboptimal. Certainly in most of the networks I envision there would be a mix of both QoS -1 and higher nodes. What about it is more difficult then I think? QoS -1 messages are just forwarded to the broker and the gateway forgets about it. No state or anything else other then the broker connection.

**Comment by ty4tw** [comment]
What to do is very easy but how to do is very complicated by my architecture.
QoS -1 was out of my scope, so it is not the partial change. The Gateway architecture have to be changed.   Aggregate Gateway will be able to handle QoS -1 in future which can forward every messages via one TCP connection.

**Comment by ty4tw** [comment]
Hi Paul
Please close this issue.

**Comment by icraggs** [comment]
I've added the enhancement label.  I think it's an interesting question which I'd like to think about.  The gateway could have some configuration as to what to do with QoS -1.  That might be quite different to the other QoSs as Tomoaki has pointed out.  QoS -1 would lack client information such a client id for instance.  Thanks for the discussion, both of you.

**Comment by icraggs** [comment]
For information, I've just added QoS -1 support to the Python broker in

https://github.com/eclipse/paho.mqtt.testing

The MQTT-SN support is limited at the moment, but I plan to keep at it, and the broker doesn't yet have a bridge (although the framework is there), but it does support V5 and V3 as well as websockets too.  With a bridge my broker will act as an aggregating gateway, like RSMB, rather than a transparent gateway like Tomoaki's, so QoS -1 makes more sense there.

**Comment by PaulKierstead** [comment]
Oh, now I’m curious! Was working on some very simple devices where -1 would
fit much better

**Comment by ty4tw** [comment]
Hi Ian, 
Aggregate Client for QoS-1  might be a one of solution.  It is a proxy for all QoS-1 clients.       
It connects to the broker through a gateway and handles ADVERTISE, GWSERCH, GWINFO, PINGREQ, PINGRESP, CONNECT, CONNACK, DISCONNECT, receiving PUBLISH(QoS-1) and sending PUBLISH(QoS0).      This one is not in the specification of MQTT-SN. But it's simple to implement.
