### ISSUE TITLE
PING Between GW <-> SN-Client

### ISSUE THREAD

**Issue by t-kitagw** [eclipse/paho.mqtt-sn.embedded-c#37]
Hello all,

Now I'm trying out this gateway and Mr. Tomoaki's ESP8266MQTTSNClient. https://github.com/ty4tw/ESP8266MQTTSNClient

I'm connecting 20 ESP8266Clients and they are gathering temperature, humidity and illuminance per minute.
I hope you inform your testing environment including the test scripts etc.
(Are you testing with MQTTSNPacket?)

In my environment, this GW is working very well!
However, sometimes clients are disconnected from GW due to some of the network trouble(I guess)
and the GW does not seem to recognize its disconnection and keep sending the publishing message.
In such a case, Your proposal, "sending DISCONNECT from GW" sounds good!

I'm thinking to try the procedure in order to improve the transmission rate between SN-Client <-> GW <-> Broker,
the one of the other way is PING between SN-Clinet <-> GW.

Kitagawa@Osaka University

**Comment by ty4tw** [comment]
GatewayTester is opened to the public. It is in the repo.
See MQTTSNGateway/GatewayTester/README.md

**Comment by t-kitagw** [comment]
Thank you very much for your information!
I'll check it out soon.

**Comment by t-kitagw** [comment]
Hi dear,

Thank you for your giving information other day.
As I tried out the GW to send DISCONNECT to unknown clients, I recognized your proposal was really good!

I have a question.
When a client periodically sends PUBLISH (QoS0) in a shorter period than T_ADV (interval time of ADVERTISE) and also when GW is down completely, the client doesn't recognize it's down for more than 15 minutes?
The value 15 minutes is recommended value for T_ADV in MQTT-SN specification.

I think this interval experimentally obtained is too longer than the purpose of MQTT's PING specification "shorter than TCP time out."
One of my idea is to send  PINGREQ and PINGRESP between SN-Client and GW.
The similar procedure is also proposed in MQTT-SN specification 6.11 "Keep Alive and PING Procedure."
In case of MQTT, even when client sends messages in a shorter period than keep alive time, the broker needn't send PINGREQ to the client due to the implementation on TCP.

As a result, my idea is sending PINGREQ from the SN-Clients to the GW during keep alive interval in spite of previous client's transmission.
I guess PINGREQ from GW to the SN-Clients is also good for keeping connection.

I'm looking forward your feedback.

Kitagawa

![ping_between_client_and_gw](https://cloud.githubusercontent.com/assets/11831277/19470495/bb99855c-955a-11e6-8068-38bf73e5b5cd.png)

**Comment by ty4tw** [comment]
1) T_ADV is configurable.  so you can make it shorter as you want.
2) Anyway you have to send PINGREQ. otherwise Broker disconnects the client.
    you can set Keep Alive time as you want. 
3) I think that using QoS1 is a answer of this case.

**Comment by ty4tw** [comment]
Dose this issue still open ?

**Comment by t-kitagw** [comment]
Thank you for your feedback and sorry for my late reply.

> 1) T_ADV is configurable. so you can make it shorter as you want.

I agree with you, but too short T_ADV makes bandwidth congestion in the network.
For clients and GW, It may or may not be a serious problem.

> 2) Anyway you have to send PINGREQ. otherwise Broker disconnects the client.
you can set Keep Alive time as you want. 
> 3) I think that using QoS1 is a answer of this case.

Exactly, it is one of the solution.
I thought My proposal might be helpful for QoS0 and made fewer message sequence than QoS1.

**Comment by ty4tw** [comment]
I think this issue should be discussed in [mqtt] mailing list.

**Comment by t-kitagw** [comment]
Thank you for your advice.
It's concerned about GW's behavior, so I thought that I should discuss here.
I close this issue.
