### ISSUE TITLE
MQTTSN Gateway -- Sends spurious congestion connack

### ISSUE THREAD

**Issue by PaulKierstead** [eclipse/paho.mqtt-sn.embedded-c#38]
Tip is "BugFix: Network can not handle EPIPE error."
The log is below. The gateway and my node get stuck in a loop doing this sequence (pretty much exactly this) over and over. Notes:
- The gateway asks for the will topic twice. When we are stuck in this state, it always asks twice. When a connect goes well, it only asks once.
- The gateway first sends an Accepted CONNACK, but then when we attempt to register a topic, it sends a congestion CONNACK.
- Even after telling the node that there is congestion, it still sends a REGACK.
- A very late second will message request appears to happen, but it looks like the logs are out of order (by a lot  -- 4 seconds !). Again, this doesn't happen when things are going well.

As a note, in the logs it might be good to more clearly differentiate between end<->Gateway and gateway<->broker other then color, as color doesn't survive cut'n'paste...

If there is any additional logging, etc. you want let me know; this happens often enough that it shouldn't be too hard to reproduce (hopefully)

```
20161014 024113.345   CONNECT           <---  Client2                             04 0C 01 02 58 43 6C 69 65 6E 74 32
20161014 024113.493   WILLTOPICREQ      --->  Client2                             06
20161014 024113.572   WILLTOPIC         <---  Client2                             07 10 74 65 73 74 32 2F 73 74 61 74 75 73
20161014 024113.662   WILLTOPICREQ      --->  Client2                             06
20161014 024113.740   WILLTOPIC         <---  Client2                             07 10 74 65 73 74 32 2F 73 74 61 74 75 73
20161014 024113.833   WILLMSGREQ        --->  Client2                             08
20161014 024113.886   WILLMSG           <---  Client2                             09 30
20161014 024113.898   CONNECT           --->  Client2                             10 24 00 04 4D 51 54 54 04 26 02 58 00 07 43 6C 69 65 6E 74 32 00 0C 74 65 73 74 32 2F 73 74 61 74 75 73 00 01 30
20161014 024113.903   CONNACK           <---  Client2                             20 02 00 00
20161014 024114.045   WILLMSG           <---  Client2                             09 30
20161014 024118.000   WILLMSGREQ        --->  Client2                             08
20161014 024118.146   CONNACK           --->  Client2                             05 00

20161014 024118.236   REGISTER    0026  <---  Client2                             0A 00 00 00 26 74 65 73 74 32 2F 73 74 61 74 75 73
20161014 024118.376   CONNACK           --->  Client2                             05 01

20161014 024118.406   CONNECT           <---  Client2                             04 0C 01 02 58 43 6C 69 65 6E 74 32
20161014 024118.494   REGACK      0026  --->  Client2                             0B 00 01 00 26 00

```

**Comment by ty4tw** [comment]
Those are normal hand shake.   
```
20161014 024113.886   WILLMSG           <---  Client2                             09 30
20161014 024113.898   CONNECT           --->  Client2                             10 24 00 04...
20161014 024113.903   CONNACK           <---  Client2                             20 02 00 00
```

 Those are extraordinary.  
 1) Before sending CONNACK to the client. Client send WILLMSG.
 2) Gateway sends WILLMSGREQ.   
```
20161014 024114.045   WILLMSG           <---  Client2                             09 30
20161014 024118.000   WILLMSGREQ        --->  Client2                             08
```

This is normal.  gateway sends CONNACK which are sent from the Broker.
```  
20161014 024118.146   CONNACK           --->  Client2                             05 00
```

Now, Gateway is expecting to receive WILLMSG because WILLMSGREQ was sent.
But, REGISTER is sent.  Therefore, Gateway sent CONNACK with error code to stop connect hand shake.
```
20161014 024118.236   REGISTER    0026  <---  Client2                         0A 00 00 ...
20161014 024118.376   CONNACK           --->  Client2                             05 01
```

1) happened several times before when the Broker can not return CONNACK immediately in case of TLS connections.    so, in such case Gateway returns CONNACK with error code. 

 but this time Gateway sent WILLMSGREQ. I will check & fix it.

**Comment by ty4tw** [comment]
Did you send

**Comment by ty4tw** [comment]
Did you  send CONNECT twice？
What kind of message was sent from Gateway after receiveing second REGISTER ?

**Comment by PaulKierstead** [comment]
The client and the gateway are stuck in a sequence of sending those messages over and over again, so the next message is the client starting over again by sending a connect. Looking at it, normally the second willmsgreq and willmsg is in sequence (I don't know why there were swapped that time). Here is the dump from a few cycles before that:
~~~~
20161014 024028.147   CONNECT           <---  Client2                             04 0C 01 02 58 43 6C 69 65 6E 74 32
20161014 024028.295   WILLTOPICREQ      --->  Client2                             06
20161014 024028.388   WILLTOPIC         <---  Client2                             07 10 74 65 73 74 32 2F 73 74 61 74 75 73
20161014 024028.473   WILLTOPICREQ      --->  Client2                             06
20161014 024028.541   WILLTOPIC         <---  Client2                             07 10 74 65 73 74 32 2F 73 74 61 74 75 73
20161014 024028.647   WILLMSGREQ        --->  Client2                             08
20161014 024028.690   WILLMSG           <---  Client2                             09 30
20161014 024028.702   CONNECT           --->  Client2                             10 24 00 04 4D 51 54 54 04 26 02 58 00 07 43 6C 69 65 6E 74 32 00 0C 74 65 73 74 32 2F 73 74 61 74 75 73 00 01 30
20161014 024028.707   CONNACK           <---  Client2                             20 02 00 00
20161014 024028.804   WILLMSGREQ        --->  Client2                             08
20161014 024028.854   WILLMSG           <---  Client2                             09 30
20161014 024028.990   CONNACK           --->  Client2                             05 00

20161014 024029.086   REGISTER    0022  <---  Client2                             0A 00 00 00 22 74 65 73 74 32 2F 73 74 61 74 75 73
20161014 024029.244   CONNACK           --->  Client2                             05 01

20161014 024029.324   CONNECT           <---  Client2                             04 0C 01 02 58 43 6C 69 65 6E 74 32
20161014 024029.417   REGACK      0022  --->  Client2                             0B 00 01 00 22 00
~~~~

Again, when things are working properly, I don't see the double topic and message requests.

**Comment by PaulKierstead** [comment]
Come to think of it, this could be a different version of #36, where it appears that the xbee network layers re-sends the last message instead of a new message, hence it sends topic request again (when it meant to send msgrequest) and msg request again when it meant to send connack. I'm not sure why it reacts badly to the register (if that is what is happening)

**Comment by ty4tw** [comment]
I could not reproduce the error.  I'm testing with UDP client. I'm stacking.

**Comment by ty4tw** [comment]
wait() method of EventQue class dose not  work correct.
This bug was fixed.

**Comment by ty4tw** [comment]
wait() method of EventQue class dose not  work correct.
This bug was fixed.   #39

**Comment by PaulKierstead** [comment]
Fixed
