### ISSUE TITLE
Questions about existing functionality of the MQTT-SN Gateway

### ISSUE THREAD

**Issue by martinvarbanov** [eclipse/paho.mqtt-sn.embedded-c#42]
So,
it's not a real issue, but I didn't know where to ask my questions.
My goal is to implement a MQTT-SN bridge to a MQTT server.
Is the MQTT-SN Gateway implementation finished? 
Because this is what I want to achieve.
Generally, form what I can see, the only working thing is the MQTT-SN Client.
Is there a Server implementation working?
If you can give me pointers what can I use from your existing MQTT and MQTT-SN implementations to build a working MQTT - MQTT-SN Bridge/Gateway.

**Comment by ty4tw** [comment]
It works as far as we(Paul and me) have tested.  So, i think that a implementation was finished.
Gateway is a application, not a library.  Therefore, it is very hard to use it as the bridge.
