### ISSUE TITLE
GW does not work when a client subscribes wildcard topic

### ISSUE THREAD

**Issue by t-kitagw** [eclipse/paho.mqtt-sn.embedded-c#45]
Hi all.
When a client subscribes wildcard topic (both + and #) and other client publish message of that topic, GW shows CPU Usage 100% and the subscriber doesn't get the publish.
And also, publisher disconnects from GW, reconnect to GW.
However GW doesn't receive CONNECT message.

**Comment by ty4tw** [comment]
Thank you for your info.
can you send me a gateway's log ?
I will reproduce and fix it.

**Comment by ty4tw** [comment]
I fixed the bug. and made a pull request.
you can try it from my forked rep. before merging the pull request.
