### ISSUE TITLE
'START_BYTE' was not declared

### ISSUE THREAD

**Issue by ribeirodanielf** [eclipse/paho.mqtt-sn.embedded-c#47]
While compiling the gateway project using `make SENSORNET=xbee`, there is an error saying STAR_BYTE is not declared.
Seems it was removed accidentally on "BugFix of Wildcard of Topic Issue #40".

`#define XMIT_STATUS_TIME_OVER    5000

#define START_BYTE 0x7e
#define ESCAPE     0x7d
#define XON        0x11
#define XOFF       0x13`

**Comment by ty4tw** [comment]
Thank you for your cooperation.
