### ISSUE TITLE
Add Travis-CI automated build and test

### ISSUE THREAD

**Issue by icraggs** [eclipse/paho.mqtt-sn.embedded-c#49]
Hi Tomoaki.

It would be very good if you could add Travis build and tests to this repository, like I have for the C client repo.  This will also allow you run Mac build and tests, if you wish.  The Travis configuration in the C client repository should help you.

**Comment by icraggs** [comment]
Obviously I meant to concentrate on the build and test of the gateway :-)

**Comment by ty4tw** [comment]
I finished to update except  env: global: secure: part.

**Comment by icraggs** [comment]
It looks like the repo doesn't have Travis integration enabled like paho.mqtt.c.  I'll open a bug for the eclipse webmaster to enable it (along with paho.mqtt.embedded-c).

**Comment by ty4tw** [comment]
Hi Ian ,
Thank you.
 Only Administrator of the repo can do it. I could  just added a yml file.

2017/05/08 19:18 "Ian Craggs" <notifications@github.com>:

**Comment by icraggs** [comment]
Travis builds are now enabled, so every push and PR should run a build if configured: 

https://travis-ci.org/eclipse/paho.mqtt-sn.embedded-c

**Comment by ty4tw** [comment]
Hi Ian,
Thanks again.
I'vegot a notification email from Toravis this morning.
So, my assignment is completed.

2017/05/09 18:14 "Ian Craggs" <notifications@github.com>:
