### ISSUE TITLE
MQTT-SN Gateway - sleepy node problem

### ISSUE THREAD

**Issue by jciupis** [eclipse/paho.mqtt-sn.embedded-c#80]
Hi,

I am using the MQTT-SN Gateway with two client nodes: first one subscribes to a topic and goes to asleep state, second one publishes data on that topic. It should result in the subscriber node getting the data in between PINGREQ and PINGRESP messages, but it happens only once. After the first keep-alive procedure done by the subscriber in asleep state, the node is kept in an undefined state. The gateway pushes PUBLISH messages outside of the PINGREQ - PINGRESP period, but does not receive PUBACK response. I have attached a log from the gateway to clarify. As you can see in the log, first PUBLISH to the sleeping client is saved and forwarded to the node between PINGREQ and PINGRESP. After the PINGRESP, the publisher node sends PUBLISH message again, but this time it is forwarded immediately, but PUBACK is not received, so the PUBLISH is retransmitted. No more PUBLISH messages are sent later from the publisher node, all the PUBLISH messages are retransmissions and not received PUBACKs.

In this log, the client is asleep only on the MQTT-SN layer so that not receiving PUBACKs is visible.
[mqttsn_gateway_log.txt](https://github.com/eclipse/paho.mqtt-sn.embedded-c/files/1284148/mqttsn_gateway_log.txt)

**Comment by ty4tw** [comment]
Thank you for your contribution.
I have fixed it.
If the problem is solved, close the issue. if not let me know i will fix it.

**Comment by jciupis** [comment]
Thank you. The problem is solved.
