### ISSUE TITLE
Clarify usage of MulticastPort and GatewayPort

### ISSUE THREAD

**Issue by sjwalke** [eclipse/paho.mqtt-sn.embedded-c#83]
Reuse of the ::unicast function within ::broadcast in SensorNetwork.cpp like this:

int UDPPort::broadcast(const uint8_t* buf, uint32_t length)
{
  return unicast(buf, length, &_grpAddr);
}

means that multicast packets (specifically, ADVERTISE) are actually being sent via the gateway port (:10000 in the default config) because the unicast socket descriptor is being used.

Is this intentional ?

**Comment by ty4tw** [comment]
Yes.
When Gateteways are in the same network, Clients have to identify which
gateway's Advertise or Gwinfo.

2017/09/12 19:06 "sjwalke" <notifications@github.com>:

**Comment by sjwalke** [comment]
Thanks @ty4tw - so in the Gateway readme where it says:

"MulticastIP and MulticastPortNo is a multicast address for ADVERTISE"

what does this mean ? Am I missing something ?

Using the default gateway.conf I never see the ADVERTISE being sent on port 1883 (I guess because it's **not** sent using _sockfdMulticast )

**Comment by ty4tw** [comment]
Readme is wrong as you said.


2017/09/12 20:23 "sjwalke" <notifications@github.com>:

**Comment by sjwalke** [comment]
That makes sense ! Will close this now, please update the readme when you can.
