### ISSUE TITLE
CONNECT primitive with empty ClientId

### ISSUE THREAD

**Issue by sjwalke** [eclipse/paho.mqtt-sn.embedded-c#86]
A misbehaving client that sends CONNECT towards the GW with a zero-length ClientId field will crash the gateway. 

Function **MQTTSNDeserialize_connect()** does not validate against the error condition:

`(data->clientID.lenstring.data == NULL)`

and hence a null string is deferenced later in the receive task (most likely by the logging functions)

**Comment by ty4tw** [comment]
Thank you for your report.  I changed to that the gateway sets a null client ID when the clientID of CONNECT is null.
