### ISSUE TITLE
Packet logging functions need buffer length checks

### ISSUE THREAD

**Issue by sjwalke** [eclipse/paho.mqtt-sn.embedded-c#91]
**MQTTGWPacket::print()** and **MQTTSNPacket::print()** do not validate the length of the output buffer. As a result, incoming payload data (e.g a broker's PUBLISH message to a subscribed client) that exceeds 478 characters will cause an out-of-bounds buffer write - with obvious consequences.

One way to defend (for both classes) would be to add a buffer limit parameter (`size_t logspace`) and use it like this

```
::print(char* pbuf, const size_t logspace)
{
  for (int i = 0; i < len; i++)
  {
    if (*pptr < (ptr+logspace-4))
    {
      sprintf(*pptr, " %02X", packetData[i]);
      *pptr += 3;
    }
  }

```

All callers of this member function need to be updated with the extra parameter (usually `sizeof(pbuf)` ) which means a total of about 20 edits across client and broker send/receive modules.

**Comment by ty4tw** [comment]
Thank you for your suggestion.

cloud you try this code ?

char* MQTTGWPacket::print(char* pbuf)
{
	uint8_t packetData[MQTTSNGW_MAX_PACKET_SIZE];
	char* ptr = pbuf;
	char** pptr = &pbuf;
	int len = getPacketData(packetData);
	int size = len > SIZE_OF_LOG_PACKET ? SIZE_OF_LOG_PACKET : len;
	for (int i = 0; i < size; i++)
	{
		sprintf(*pptr, " %02X", packetData[i]);
		*pptr += 3;
	}
	**pptr = 0;
	return ptr;
}

**Comment by ty4tw** [comment]
Try Develop branch.

**Comment by sjwalke** [comment]
I'll try this out, but I'm still concerned that you have a sprintf() to an address that can be beyond the end of the buffer (because of the +3 increment)....

**Comment by ty4tw** [comment]
Is (SIZE_OF_LOG_PACKET + 5 )* 3  too short ?   which means + 5 is not enough.
I have no environment to test now.   could you teach me the right length?  

int BrokerRecvTask::log(Client* client, MQTTGWPacket* packet)
{
	char pbuf[(SIZE_OF_LOG_PACKET + 5 )* 3];
	char msgId[6];
	int rc = 0;
