### ISSUE TITLE
qos -1 issue

### ISSUE THREAD

**Issue by cyqsign** [eclipse/paho.mqtt-sn.embedded-c#92]
I am using the paho.mqtt-sn.embedded-c and emqtt/emq-sn on Linux platform .
In my test platform,there are two clients.Client A is used to publish message,and Client B is used to subscribe message.
Client A public info:
topic:"hello"
payload:"test"
qos:-1

**I find Client B can not receive any message.**So I trace log :

In client A
Serialize publish message is :10 0C 60 00 05 00 00 68 65 6C 6C 6F 74 65 73 74
10:lenth
0C:PUBLISH FLAG
60: qos is -1
00 05
00 00: packet id
68 65 6C 6C 6F : hello
74 65 73 74 :test

**I find the topic length(qos = -1) in MQTTSNSerialize_publish(paho.mqtt-sn.embedded-c/MQTTSNPacket/src/MQTTSNSerializePublish.c) like this:
if (topic.type == MQTTSN_TOPIC_TYPE_NORMAL && qos == 3)
{
/ special arrangement for long topic names in QoS -1 publishes. The length of the topic is in the topicid field /
writeInt(&ptr, topic.data.long_.len); / topic length /
}**

**From the mqtt-sn spec, there no topic length field.**
Could you please tell me why? @icraggs

**Comment by ty4tw** [comment]
Gateway does not support QoS -1.

**Comment by ty4tw** [comment]
In the spec, topic length is 2 octets.

6.8 PUBLISH with QoS Level -1
TopicId field: value of the pre-defined topic id or of the short topic name;

6.7 Pre-defined topic ids and short topic names
A “short” topic name is a topic name that has a fixed length of two octets.
