### ISSUE TITLE
Use secure connection to the broker by default?

### ISSUE THREAD

**Issue by jue89** [eclipse/paho.mqtt-sn.embedded-c#99]
Hi!

As far as I understand the code, MQTTSNGateway uses only secure connections if every possible client ID is listed in the ClientsList and the keyword ```secureConnection``` is attached to the client. What do you think of using secure connection by default if ```BrokerSecurePortNo```, ```RootCAfile``` (or ```RootCApath```), ```CertKey``` and ```PrivateKey``` is given?

Or do you have any concerns?

Thank you!

**Comment by ty4tw** [comment]
Current secure connection is only between Gateway and Broker.
If any client can connect the Gateway there's no meaning of secure connection.
So, the authentication functionality is a minimum requirement for the gateway.
I thought like that.
